/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.prevarisc.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Table tampon pour mise à jour des adresse de Prevarisc
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Adresserue implements Serializable {

	private static final long serialVersionUID = 611656831;

	private Long   idRue;
	private String libelleRue;
	private String numinseeCommune;

	public Adresserue() {}

	public Adresserue(Adresserue value) {
		this.idRue = value.idRue;
		this.libelleRue = value.libelleRue;
		this.numinseeCommune = value.numinseeCommune;
	}

	public Adresserue(
		Long   idRue,
		String libelleRue,
		String numinseeCommune
	) {
		this.idRue = idRue;
		this.libelleRue = libelleRue;
		this.numinseeCommune = numinseeCommune;
	}

	public Long getIdRue() {
		return this.idRue;
	}

	public Adresserue setIdRue(Long idRue) {
		this.idRue = idRue;
		return this;
	}

	public String getLibelleRue() {
		return this.libelleRue;
	}

	public Adresserue setLibelleRue(String libelleRue) {
		this.libelleRue = libelleRue;
		return this;
	}

	public String getNuminseeCommune() {
		return this.numinseeCommune;
	}

	public Adresserue setNuminseeCommune(String numinseeCommune) {
		this.numinseeCommune = numinseeCommune;
		return this;
	}
}
