/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.pdi.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModeleMessage implements Serializable {

	private static final long serialVersionUID = -798166052;

	private Integer idmodele;
	private String  corps;
	private String  objet;

	public ModeleMessage() {}

	public ModeleMessage(ModeleMessage value) {
		this.idmodele = value.idmodele;
		this.corps = value.corps;
		this.objet = value.objet;
	}

	public ModeleMessage(
		Integer idmodele,
		String  corps,
		String  objet
	) {
		this.idmodele = idmodele;
		this.corps = corps;
		this.objet = objet;
	}

	public Integer getIdmodele() {
		return this.idmodele;
	}

	public ModeleMessage setIdmodele(Integer idmodele) {
		this.idmodele = idmodele;
		return this;
	}

	public String getCorps() {
		return this.corps;
	}

	public ModeleMessage setCorps(String corps) {
		this.corps = corps;
		return this;
	}

	public String getObjet() {
		return this.objet;
	}

	public ModeleMessage setObjet(String objet) {
		this.objet = objet;
		return this;
	}
}
