/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.prevarisc;


import fr.sdis83.remocra.db.model.prevarisc.tables.Adressecommune;
import fr.sdis83.remocra.db.model.prevarisc.tables.Adresserue;
import fr.sdis83.remocra.db.model.prevarisc.tables.Etablissement;
import fr.sdis83.remocra.db.model.prevarisc.tables.RemocraCommune;
import fr.sdis83.remocra.db.model.prevarisc.tables.RemocraRue;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Prevarisc extends SchemaImpl {

	private static final long serialVersionUID = 1843770641;

	/**
	 * The reference instance of <code>prevarisc</code>
	 */
	public static final Prevarisc PREVARISC = new Prevarisc();

	/**
	 * No further instances allowed
	 */
	private Prevarisc() {
		super("prevarisc");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Adressecommune.ADRESSECOMMUNE,
			Adresserue.ADRESSERUE,
			Etablissement.ETABLISSEMENT,
			RemocraCommune.REMOCRA_COMMUNE,
			RemocraRue.REMOCRA_RUE);
	}
}
