= SDIS Remocra - Définition des cartes

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

:experimental:
:icons: font

:toc:

:numbered:

link:../index{outfilesuffix}[Retour à l'accueil]

link:../Manuel%20administration{outfilesuffix}[Retour au manuel d'administration]

'''


*Paramétrage des cartes*

. link:Couche%20GeoServer{outfilesuffix}[Création d'une couche dans GeoServer]
. link:Couches%20Remocra{outfilesuffix}[Référencement des couches et sécurisation des accès]
. **Définition des cartes**

'''


Les cartes sont configurées via des fichiers JSON.


== Liste des fichiers des cartes ==

Les fichiers des cartes sont les suivants :

[source]
----
/var/remocra/html/js/app/remocra/features/cartographie/data/carte.json
/var/remocra/html/js/app/remocra/features/hydrants/data/carte.json
/var/remocra/html/js/app/remocra/features/hydrants/data/carte-requete-selection.json
/var/remocra/html/js/app/remocra/features/oldebs/data/carte.json
/var/remocra/html/js/app/remocra/features/permis/data/carte.json
/var/remocra/html/js/app/remocra/features/rci/data/carte.json
/var/remocra/html/js/app/remocra/features/dfci/data/carte.json
/var/remocra/html/js/app/remocra/features/adresses/data/carte.json
/var/remocra/html/js/app/remocra/features/risques/data/carte.json
/var/remocra/html/js/app/remocra/features/prescrits/data/carte.json
----


== Exemple de définition de carte ==

Exemple de carte :

./var/remocra/html/js/app/remocra/features/adresses/data/carte.json
[source,js]
----
{
    "libelle": "Légende",
    "items": [{
        "libelle": "Groupe spécifique",
        "items": [{
                "type": "specific",
                "libelle": "Mes alertes",
                "id": "alertesLayer",
                "scale_min": "0",
                "scale_max": "90708",
                "visibility": true,
                //"opacity":0.5,
                "interrogeable": true,
                "items": [
                    {
                        "libelle": "En attente de traitement",
                        "image": "alertes/checking.png"
                    },
                    {
                        "libelle": "Acceptée",
                        "image": "alertes/ok.png"
                    },
                    {
                        "libelle": "Refusée",
                        "image": "alertes/ko.png"
                    }
        ]
            }
    ]
    }, {
        "libelle": "Groupe SDIS",
        "items": [{
            "type": "wms",
            "libelle": "Administratif",
            "id": "administratifLayer",
            "layers": "remocra:ADMINISTRATIF",
            "url": "/remocra/geoserver/remocra/wms",
            "projection": "EPSG:900913",
            "sld": null,
            "scale_min": "0",
            "scale_max": "362834",
            "visibility": false,
            "opacity": 1,
            "interrogeable": true,
            "items": [
                {
                    "libelle": "CIS",
                    "image": "administratif/bat_cis.png"
                },
                {
                    "libelle": "Commune",
                    "image": "administratif/commune.png"
                },
                {
                    "libelle": "Departement",
                    "image": "administratif/departement.png"
                }
        ]
    }, {
            "type": "wms",
            "libelle": "Habillage urbain",
            "id": "habillageUrbainLayer",
            "layers": "remocra:HABILLAGE_URBAIN",
            "url": "/remocra/geoserver/remocra/wms",
            "projection": "EPSG:900913",
            "sld": null,
            "scale_min": "0",
            "scale_max": "362834",
            "visibility": false,
            "opacity": 1,
            "interrogeable": false,
            "items": [{
                "keepsize": true,
                "image": "/remocra/geoserver/remocra/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LEGEND_OPTIONS=bgColor:0xf4f4f4;fontStyle:italic;fontColor:0x808080;fontAntiAliasing:true&LAYER=remocra:HABILLAGE_URBAIN"
        }]
    }]
    }, {
        "libelle": "Groupe divers WMTS",
        "items": [{
            "type": "wmts",
            "base_layer": true,
            "libelle": "Orthophotographie Auvergne CRAIG/IGN 2013",
            "id": "ab27573715e8e84f20879a014e24a341",
            "scale_min": "0",
            "scale_max": "1000000",
            "visibility": true,
            "opacity": 1,
            "interrogeable": false,
            "items": null,
            "format": "image/jpeg",
            "layers": "ortho_2013",
            "url": "http://tiles.craig.fr/ortho/service",
            "styles": [{
                "id": "default",
                "libelle": ""
                }],
            "tileMatrixSet": {
                "nom": "webmercator",
                "resolution_min": 0.0746455354347,
                "resolution_max": 156543.0339281199800
            }
    }]
    }, {
        "libelle": "Groupe IGN",
        "items": [{
            "type": "ign",
            "libelle": "Parcelles cadastrales",
            "id": "cadastreLayer",
            "scale_min": "0",
            "scale_max": "22677",
            "visibility": false,
            "opacity": 0.5,
            "format": "image/png",
            "layers": "CADASTRALPARCELS.PARCELS",
            "items": [
                {
                    "libelle": "Cadastre",
                    "image": "ign/cadastre.png"
                }
        ]
        }, {
            "type": "ign",
            "libelle": "Cartes IGN",
            "id": "carteLayer",
            "scale_min": "5669",
            "scale_max": "999999999",
            "visibility": false,
            "opacity": 1,
            "format": null,
            "style": "normal",
            "layers": "GEOGRAPHICALGRIDSYSTEMS.MAPS",
            "items": [
                {
                    "libelle": "Cartes IGN",
                    "image": "ign/carte.png"
                }
        ]
        }, {
            "base_layer": true,
            "type": "ign",
            "libelle": "Photos aériennes",
            "id": "photoLayer",
            "scale_min": "0",
            "scale_max": "999999999",
            "visibility": true,
            "opacity": 1,
            "format": null,
            "style": "normal",
            "layers": "ORTHOIMAGERY.ORTHOPHOTOS",
            "items": [
                {
                    "libelle": "Photos aériennes",
                    "image": "ign/photo.png"
                }
        ]
        }]
    }, {
        "libelle": "Autres fonds",
        "items": [{
            "type": "osm",
            "libelle": "Carte OSM",
            "id": "osm",
            "visibility": false,
            "opacity": 0.5,
            "items": [
                {
                    "libelle": "OSM",
                    "image": "osm/osm.png"
                }
        ]
        }, {
           "type": "tms",
           "libelle": "Atlas parcellaire",
           "id": "atlas",
           "visibility": true,
           "opacity": 0.8,
           "base_layer": false,
           /* Niveaux 16 à 18 */
           "min_resolution": 0.5971642834779396,
           "max_resolution": 2.3886571339117584,
           "url": "https://remocra.sdisxx.fr/tms/",
           "layername": "parcellaire",
           "format": "png"
       }]
    }]
}
----


== Définition d'une carte ==

Les niveaux hiérarchiques sont les suivants :

* Carte
** Groupe
*** Couche
**** Elément de légende

Pour l'ensemble des cartes, on retrouvera généralement le goupe "Fonds IGN" qui comporte la configuration des couches IGN.
Pour les autres, on a deux types de fonds :

* les couches génériques : WMS, WMTS, IGN, OSM, TMS
** par exemple celle qui porte l'id _administratifLayer_ dans l'exemple
* les couches spécifiques
** par exemple celle qui porte l'id _alertesLayer_ dans l'exemple


=== Options communes ===

Les options communes aux couches sont les suivantes :
[source,js]
----
"type" : "specific", "wms", "wmts", "ign" ou "osm" ou "tms"
"libelle" : "Administratif"
"id" : "administratifLayer"
"projection" : "EPGS:3857", EPSG:900913", etc.
"scale_min" : "0"
"scale_max" : "362834"
"visibility" : false
"opacity" : 1
"interrogeable" : true
"items" : []
"class" : "hidden" (ne pas faire apparaître une couche dans la légende)
----

=== Options couches génériques ===

==== Pour les couches de type "wms"
[source,js]
----
"type" : "wms"
"layer" : "remocra:ADMINISTRATIF"
"url" : "/remocra/geoserver/remocra/wms"
"sld" : null
----

Remarque, deux proxies existent pour accéder aux couches du serveur GeoServer de la plateforme :

* /remocra/geoserver/{workspace}/wms : proxy GeoServer avec
** gestion des workspaces
** sécurisé finement : couche accessible publiquement ou qui nécessite une authentification, profils avec accès complet ou limités à la zone de compétence. Cf. link:Couches%20Remocra{outfilesuffix}[configuration des couches].
** Exemple : */remocra/geoserver/remocra/wms*
* /remocra/proxy/wms : ancien proxy GeoServer (éviter de l'utiliser) avec
** un seul workspace : _remocra_
** deux niveaux d'accès public / utilisateurs authentifiés limités à la zone de compétence

==== Pour les couches de type "wmts"

Les informations sont déductibles des Capabilities du service :
[source,js]
----
"type" : "wmts"
"format" : "image/png" ou "image/jpeg"
"layers" : "ortho_2013", "CADASTRALPARCELS.PARCELS" etc.
"url" : "http://tiles.craig.fr/ortho/service"
"style" : "normal" (recherche du premier élément de styles en cas d'absence)
"styles" : [{ "id": "default", "libelle": "" }]
"tileMatrixSet": { "nom": "webmercator", "resolution_min": 0.0746455354347, "resolution_max": 156543.0339281199800 }
----

==== Pour les couches de type "ign"
[source,js]
----
"type" : "ign"
"format" : "image/png"
"layers" : "CADASTRALPARCELS.PARCELS" ou "GEOGRAPHICALGRIDSYSTEMS.MAPS" "ORTHOIMAGERY.ORTHOPHOTOS", "GEOGRAPHICALGRIDSYSTEMS.MAPS.BDUNI.J1" etc.
"style" : "normal"
----

Remarque, link:Demande%20cle%20IGN{outfilesuffix}[une clé IGN] doit être paramétrée pour le bon fonctionnement de ce type de couche.

==== Pour les couches de type "osm"
[source,js]
----
"type" : "osm"
"urls" : facultatif. Permet de changer les URLs par défaut. Exemple : ['http://a.tile.openstreetmap.org/${z}/${x}/${y}.png', 'http://b.tile.openstreetmap.org/${z}/${x}/${y}.png', 'http://c.tile.openstreetmap.org/${z}/${x}/${y}.png']
"tile_options" : facultatif. Lorsqu'on paramètre un autre serveur (via "urls"), il est possible que ce dernier ne renvoie pas les entêtes Access-Control-Allow-Origin. Dans ce cas, il peut être nécessaire de définir la valeur {"crossOriginKeyword": null} pour permettre au navigateur d'afficher les tuiles.
----

==== Pour les couches de type "tms"
[source,js]
----
"type" : "tms"
/* Exemple pour afficher la couche des niveaux 16 à 18 */
"min_resolution": 0.5971642834779396
"max_resolution": 2.3886571339117584
"url": "https://remocra.sdisxx.fr/tms/"
"layername": "parcellaire"
"format": "png" (par défaut) ou "jpg"
"version": "1.0.0" par défaut
----
Les résolutions sont exprimées en 3857 ; se référer aux link:https://github.com/atolcd/sdis-remocra/blob/master/remocra/src/main/webapp/js/app/remocra/widget/map/Map.js[résolutions définies ici].


=== Options couches spécifiques ===

==== Couches spécifiques

[source,js]
----
"type" : "specific"
"id" : "alertesLayer" ou "hydrantLayer" ou "prescritLayer" ou "risquesExpressLayer"
----

Pour les couches spécifiques "hydrantLayer" et "prescritLayer", on précise également la stratégie :
[source,js]
----
"stategy" : "bbox"
----

== Images de la légende ==

Pour chaque couche, la légende est déterminée par les _items_ (tableau). Exemples de légendes :
[source,json]
----
# Les imagettes sont placées sous la couche :
"items":[
    {"libelle":"En attente de traitement","image":"alertes/checking.png"},
    {"libelle":"Acceptée","image":"alertes/ok.png"},
    {"libelle":"Refusée","image":"alertes/ko.png"}
]}


# Lorsque la légende est composée d'un seul élément, l'image est placée à gauche du nom de la couche :
"items":[
    {"libelle":"Cadastre","image":"ign/cadastre.png"}
]


# On peut utiliser une légende produite par GeoServer. Dans ce cas, on utilise le proxy en précisant a minima l'attribut LAYER.
# L'image qui n'a pas de libellé associé ici sera placée sous la couche concernée. La taille de l'image produite est conservée (paramètre keepsize) :
"items":[{
    "keepsize":true,
    "image":"/remocra/geoserver/remocra/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LEGEND_OPTIONS=bgColor:0xf4f4f4;fontStyle:italic;fontColor:0x808080;fontAntiAliasing:true&LAYER=remocra:HABILLAGE_URBAIN"
}]
----

Les images nécessaires à la construction de la légende sont déposées dans (on peut utiliser des sous-répertoires) :

 /var/remocra/html/images/remocra/cartes/legende

Par exemple pour les images de l'exemple qui précède, on a les images suivantes :

[source]
----
/var/remocra/html/images/remocra/cartes/legende/alertes/checking.png
/var/remocra/html/images/remocra/cartes/legende/alertes/ok.png
/var/remocra/html/images/remocra/cartes/legende/alertes/ko.png
----

== Cartes spécifiques ==

=== Module PEI, localisation ===

Pour le *module PEI*, un comportement particulier facultatif permet de coupler 2 couches :

* "hydrantLayer" : couche vectorielle utilisée pour la manipulation (sélection d'objets),
* "hydrantLayerWms" : couche WMS dédiée à l'affichage.

La couche "hydrantLayerWms" peut être masquée dans la légende avec l'attribut `"class" : "hidden"`.
D'autre part, la couche "hydrantLayerWms" est synchronisée avec la couche "hydrantLayer" sur les propriétés suivantes :

* visibilité
* transparence
* rafraîchissement

Ainsi, l'utilisateur ne voit/manipule qu'une couche et le style peut être paramétré au niveau de GeoServer.

Exemple de configuration de couches dans la carte des PEI :

Couche "hydrantLayer" (configuration classique) :
[source,js]
----
{
    "type": "specific",
    "stategy": "bbox",
    "libelle": "PIBI / PENA",
    "id": "hydrantLayer",
    "maxResolution": 3.0,
    "visibility":true,
    "interrogeable": true,
    "items":[ ]
}
----

Couche "hydrantLayerWms" (noter `"id": "hydrantLayerWms"` et `"class": "hidden"`, ) :
[source,js]
----
{
    "id": "hydrantLayerWms",
    "class": "hidden",
    "interrogeable": false,
    "layers": "remocra:EAU",
    "libelle": "Eau",
    "opacity": 1,
    "projection": "EPSG:900913",
    "scale_max": "362834",
    "scale_min": "0",
    "sld": null,
    "type": "wms",
    "url": "/remocra/geoserver/remocra/wms",
    "visibility": true
}
----

Remarque :

* Pour éviter de perturber l'utilisateur, on harmonise les plages de visibilité avec les paramètres `\*Resolution` et `scale*` (ce n'est pas le cas dans l'exemple).


=== Module PEI, recherches et analyses ===

La *carte "Recherches et analyses" du module PEI s'appuie sur une couche de type `wms` avec l'identifiant `zonesLayer`* (c'est un prérequis). Exemple de couche paramétrée dans le fichier fichier `/var/remocra/html/js/app/remocra/features/hydrants/data/carte-requete-selection.json` :
[source,json]
----
{
  "type": "wms",
  "libelle":"Résultat d'analyse<br/>",
  "id":"zonesLayer",
  "layers":"remocra:v_requete_modele_selection_detail",
  "url":"/remocra/geoserver/remocra/wms",
  "projection":"EPSG:900913",
  "sld":null,
  "scale_min":"0",
  "scale_max":"362834",
  "visibility":true,
  "opacity":1,
  "interrogeable": true
}
----

=== Module Crise ===

La *carte du module crise s'appuie sur une couche de type `wms` avec l'identifiant `893bb7520e7fb036d665661847628994`* (c'est un prérequis).
En plus, un groupe de couches *`additional`* qui sert à contenir les couches mobilisés pour la crise (prérequis). 
Exemple de carte par défaut du module
`/var/remocra/html/js/app/remocra/features/crises/data/carte.json` :
[source,json]
----
{
  "libelle":"Légende",
  "items":[{
    "libelle":"Crise",
    "items":[{
      "type" : "specific",
      "id" : "893bb7520e7fb036d665661847628994",
      "libelle" : "Évènements",
      "visibility" : true,
      "opacity" : 1
    },{
      "type" : "wms",
      "id" : "selection",
      "libelle" : "Résultat d'analyse",
      "url":"/remocra/geoserver/remocra/wms",
      "visibility" : true,
      "opacity" : 1,
      "sld": null,
      "scale_min":"0",
      "scale_max":"362834",
      "layers":"remocra:v_requete_modele_selection_detail",
      "styles" : [{ "id": "default", "libelle": "" }],
      "projection": "EPSG:900913",
      "interrogeable": true
    }]
  },{
    "libelle":"Couches mobilisées",
    "code": "additional",
    "items":[]
  },{
    "libelle":"Fonds IGN",
    "items":[{
      "type" : "wmts",
      "libelle" : "Cartes IGN",
      "id" : "d05123efca65d99b029d5781a1c34ef5",
      "scale_min" : "0",
      "scale_max" : "1000000",
      "visibility" : true,
      "opacity" : 1,
      "interrogeable" : false,
      "items" : null,
      "num_zoom_levels" : null,
      "format" : "image/jpeg",
      "layers" : "GEOGRAPHICALGRIDSYSTEMS.MAPS",
      "url" : "https://wxs.ign.fr/pratique/geoportail/wmts",
      "styles" : [{
        "legende": "/remocra/ext-res/images/remocra/cartes/legende/ign/carte.png",
        "id" : "normal",
        "libelle" : "Légende générique"
      }],
      "tileMatrixSet" : {
        "nom" : "PM",
        "resolution_min" : 0.25,
        "resolution_max" : 2445.9849051256400
      }
    }

    ]
  }
  ]}

----


_Aide technique : tutoriels link:http://www.w3schools.com/json[JSON] sur w3schools.com, link:http://docs.geoserver.org/[Documentation GeoServer] sur geoserver.org et link:http://ign.fr/[IGN]_
