/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.pg_toast_temp_7;


import javax.annotation.Generated;

import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgToastTemp_7 extends SchemaImpl {

	private static final long serialVersionUID = -423646000;

	/**
	 * The reference instance of <code>pg_toast_temp_7</code>
	 */
	public static final PgToastTemp_7 PG_TOAST_TEMP_7 = new PgToastTemp_7();

	/**
	 * No further instances allowed
	 */
	private PgToastTemp_7() {
		super("pg_toast_temp_7");
	}
}
