// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.sdis83.remocra.domain.remocra;

import fr.sdis83.remocra.domain.remocra.Permis;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Permis_Roo_Configurable {
    
    declare @type: Permis: @Configurable;
    
}
