= SDIS Remocra - Manuel d'installation V2

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

:experimental:
:icons: font

:toc:

:numbered:

link:../index{outfilesuffix}[Retour à l'accueil]

'''
== Livraison ==

On part d'un serveur Debian/Utbuntu vierge:

Créer le répertoire d'accueil des éléments d'installation : `mkdir /livraison`

Créer le répertoire d'accueil des éléments de docker : `mkdir /etc/docker_remocra`

Déposer les scripts du répertoire _vagrantV2_ :

* _vagrantV2/docker_ =>  _/etc/docker_remocra_
* _vagrantV2/livraison_ => _/livraison_

Rendre les scripts exécutables :

[source,sh]
----
chmod u+x /livraison/*.sh
chmod u+x /etc/docker_remocra/*.sh
----

== Lancement de l'installation ==

* Lancer l'installation : `/livraison/launcher.sh 2>&1 | tee /livraison/launcher.log`

== Restauration des bases de données ==
* Créer la base remocra `createdb remocra -E UTF8 remocra`
* Créer l'utilisateur remocra `psql remocra -c "CREATE user remocra WITH SUPERUSER ENCRYPTED PASSWORD '${REMOCRA_DB_PASSWORD:-xxxxx}'"`;
* Dans le cas d'upgrade : Restaurer le backup2.5 préalablement préparé // TODO lien vers le script d'upgrade

[source,sh]
----
su postgres
pg_restore -d remocra -U remocra '/livraison/db/remocra-2.5.backup'
----
* Restaurer remocra_ref_pdi (à récupérer dans le depot github)
[source,sh]
----
pg_restore -d remocra_ref_pdi -U remocra 'home/postgres/pdi_db/000_remocra_pdi_all.sql'
----

* Récupérer les patches du /home/postgres/remocra_db et jouer les patches manquants 

 Ex: `psql -d remocra  -f '/home/postgres/remocra_db/patches/134/134.sql'`
 
* Jouer le script de montée de données (dans le cas de migration) 

[source,sh]
----
psql remocra -c "update remocra.param_conf set valeur='/home/pdi/remocra.properties' where cle='PDI_FICHIER_PARAMETRAGE'"
psql remocra -c "update remocra.param_conf set valeur='http://localhost:8090/geoserver' where cle='WMS_BASE_URL'"
----

* Récupérer le contenu de /var/remocra de l'ancien serveur 

* Récupérer les fichiers suivants du depot github 

   `/var/remocra/modeles/processus_etl` 
   `/var/remocra/modeles/xsd`

* récupérer kettle.properties  de `/home/postgres/.kettle/kettle.properties`
* récupérer repositories.xml  de `/home/postgres/.kettle/repositories.xml`
* récupérer remocra.properties  de `/home/postgres/remocra_pdi/remocra.properties`

[source,sh]
----
mv /kettle.properties  /etc/docker_remocra/.docker/jobs-common/
mv /remocra.properties  /etc/docker_remocra/.docker/jobs-common/
mv /repositories.xml  /etc/docker_remocra/.docker/jobs-4.4/.ketlle/
----

* Se connecter au docker registry afin de récupérer les images docker (Le login/mot de passe sont fournis par atol)
 
 `docker login client-docker-registry.atolcd.com`
 
* Lancer le script /etc/docker-remocra/build_containers.sh

* Lancer le script /livraison/planification_traitements.sh (à adapter par SDIS)
