= SDIS Remocra - Manuel d'installation V2

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

:experimental:
:icons: font

:toc:

:numbered:

link:../index{outfilesuffix}[Retour à l'accueil]

'''

== Préambule ==
L'utilisation de REMOcRA derrière un VPN est fortement recommandée car la stack technique comporte des composants vieillissants voire non maintenus, pouvant comporter des failles de sécurité.

Les prérequis actuels pour l'installation d'un REMOcRA sur une seule machine sont les suivants

* Nombre de cpu : 8
* Mémoire vive : 8Go
* Espace disque : >= 50Go
* OS : Debian 10 ou Ubuntu 20.04
* Serveur vierge avec un accès ssh (droits *root*)

Attention, en cas d'installation sur une Debian 11, une adaptation des scripts de livraison est à prévoir car le paquet postgis en version 2.5 n'est plus téléchargeable depuis les dépôts officiels, il faut donc basculer sur une version 3.3 (et donc un postgres 15) ; les effets de bord sont à qualifier

== Livraison ==

On part d'un serveur Debian/Ubuntu vierge. Les fichiers à récupérer le sont depuis ce repo github.
Ce fichier décrit pas à pas une installation remocra où tous les composants sont situés sur un même
serveur

* Créer le répertoire d'accueil des éléments d'installation :
[source,sh]
----
mkdir /livraison
----

* Créer le répertoire d'accueil des éléments de docker :
[source,sh]
----
mkdir /etc/docker_remocra
----

* Récupérer le /var/remocra

* Déposer les fichiers du répertoire _vagrantV2_ :

** _vagrantV2/docker_ =>  _/etc/docker_remocra_
** _vagrantV2/livraison_ => _/livraison_
** _server/sdis_remocra/var/remocra_ => _/var/remocra_ (depuis le repos interne ou un serveur existant)

* Récupérer les dossiers nécessaires à la base de donnée dans le dossier _livraison_ :
** /server/sdis-remocra/home/postgres/remocra_db
** /server/sdis-remocra/home/postgres/pdi_db

* Créer l'utilisateur applicatif remocra. Cet utilisateur doit impérativement avoir son UID et GID à 2000 (valeurs avec
lesquelles l'image docker a été générée par AtolCD)
[source,sh]
----
groupadd -g 2000 remocra
useradd -u 2000 -g remocra remocra
----

* Affecter les droits à l'utilisateur remocra:
[source,sh]
----
chown -R remocra:remocra /etc/docker_remocra
chown -R remocra:remocra /var/remocra

----
* Rendre les scripts exécutables :

[source,sh]
----
chmod u+x /livraison/*.sh
----

== Lancement de l'installation ==
* Adapter le script /livraison/launcher.sh afin d'indiquer des mots de passe pour les users *postgres* et *remocra* de la base de données
[source,sh]
----
export USER_POSTGRES_DB_PASSWORD=${USER_POSTGRES_DB_PASSWORD:-xxxxxxx}
export REMOCRA_DB_PASSWORD=${REMOCRA_DB_PASSWORD:-xxxxxx}
----
* Lancer l'installation :
[source,sh]
----
/livraison/launcher[ForDebian/ForUbuntu].sh 2>&1 | tee /livraison/launcher[ForDebian/ForUbuntu].log
----
*Attention : dans le cas d'un Debian 11, adapter le script _install_base_debian.sh_ afin d'installer
la version 3.3 de PostGIS*

== Restauration des bases de données ==
* Créer l'utilisateur remocra ainsi que les rôles template (adapter la première ligne comme à l'étape ci-dessus)
[source,sh]
----
su postgres
psql -c "CREATE user remocra WITH SUPERUSER ENCRYPTED PASSWORD '${REMOCRA_DB_PASSWORD:-xxxxxx}'";
psql -c "CREATE ROLE user_template NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN";
psql -c "CREATE ROLE sgo_template NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN";
----

* Créer la base remocra et initialiser les données (l'utilisation d'un dump est également possible)
[source,sh]
----
createdb remocra -E UTF8 remocra
cd /livraison/remocra_db
psql -h localhost -U remocra -d remocra -f '000_remocra_all.sql'
----

* Vérifier que la base est bien à jour
[source,sh]
----
psql -h localhost -U remocra -d remocra -c "SELECT max(numero) FROM remocra.suivi_patches";
----

Si le numéro qui s'affiche n'est pas le numéro du patch le plus récent disponible, passer les patches
manquants *dans l'ordre* situés dans `/livraison/remocra_db/patches`

* Restaurer remocra_ref_pdi (à récupérer dans le depot github)
[source,sh]
----
createdb remocra_ref_pdi -E UTF8 remocra
psql -d remocra_ref_pdi -U remocra -f '/livraison/remocra_pdi/000_remocra_pdi_all.sql'
----

== Images docker ==

* Déposer les fichiers  kettle.properties/ repositories.xml / remocra.properties dans /etc/docker_remocra

* Se connecter au docker registry afin de récupérer les images docker (Le login/mot de passe sont fournis par atol)
 
[source,sh]
----
 docker login client-docker-registry.atolcd.com
----

* Vérifier les variables d'environnement dans  :
** remocra.properties
** repositories.xml
** kettle.properties
** .env

* Vérifier les paramètres renseignés dans la table remocra.param_conf. Une partie de ces paramètres écraseront les valeurs présentes dans le fichier remocra.properties lors du lancement des containers des jobs PDI afin que la configuration depuis l'interface remocra impacte les autres containers
 
* Démarrer les containers docker
[source,sh]
----
cd /etc/docker_remocra
docker-compose up -d
----

CAUTION: Après avoir lancé les conteneurs, il se peut que le répertoire /etc/docker_remocra/.docker ait été créé en `root`, auquel cas les conteneurs ne démarreront pas. Vérifier et exécuter un `chown remocra: /etc/docker_remocra.docker` en cas de besoin




* Lancer le script /livraison/planification_traitements.sh (à adapter par SDIS)

== Pour aller plus loin ==

* Vérifier le bon fonctionnement de GeoServer: base à interroger, protocoles à utiliser (WMS, WFS, etc)

* Mettre en place la link:../administration/Page%20d%20accueil%20privee{outfilesuffix}[page d'accueil privée]
