/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.couverture_hydraulique.tables;


import com.vividsolutions.jts.geom.Geometry;

import fr.sdis83.remocra.db.converter.GeometryBinding;
import fr.sdis83.remocra.db.model.couverture_hydraulique.CouvertureHydraulique;
import fr.sdis83.remocra.db.model.couverture_hydraulique.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Batiments extends TableImpl<Record> {

	private static final long serialVersionUID = -663739989;

	/**
	 * The reference instance of <code>couverture_hydraulique.batiments</code>
	 */
	public static final Batiments BATIMENTS = new Batiments();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>couverture_hydraulique.batiments.id</code>.
	 */
	public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>couverture_hydraulique.batiments.geometrie</code>.
	 */
	public final TableField<Record, Geometry> GEOMETRIE = createField("geometrie", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"), this, "", new GeometryBinding());

	/**
	 * The column <code>couverture_hydraulique.batiments.etude</code>.
	 */
	public final TableField<Record, Long> ETUDE = createField("etude", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>couverture_hydraulique.batiments</code> table reference
	 */
	public Batiments() {
		this("batiments", null);
	}

	/**
	 * Create an aliased <code>couverture_hydraulique.batiments</code> table reference
	 */
	public Batiments(String alias) {
		this(alias, BATIMENTS);
	}

	private Batiments(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Batiments(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, CouvertureHydraulique.COUVERTURE_HYDRAULIQUE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_BATIMENTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.BATIMENT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.BATIMENT_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.BATIMENTS__FK_ETUDE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Batiments as(String alias) {
		return new Batiments(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Batiments rename(String name) {
		return new Batiments(name, null);
	}
}
