/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.couverture_hydraulique.tables;


import com.vividsolutions.jts.geom.Geometry;

import fr.sdis83.remocra.db.converter.GeometryBinding;
import fr.sdis83.remocra.db.model.couverture_hydraulique.CouvertureHydraulique;
import fr.sdis83.remocra.db.model.couverture_hydraulique.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pei extends TableImpl<Record> {

	private static final long serialVersionUID = 1462513424;

	/**
	 * The reference instance of <code>couverture_hydraulique.pei</code>
	 */
	public static final Pei PEI = new Pei();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>couverture_hydraulique.pei.id</code>.
	 */
	public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>couverture_hydraulique.pei.identifiant</code>.
	 */
	public final TableField<Record, Long> IDENTIFIANT = createField("identifiant", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>couverture_hydraulique.pei.geometrie</code>.
	 */
	public final TableField<Record, Geometry> GEOMETRIE = createField("geometrie", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"), this, "", new GeometryBinding());

	/**
	 * The column <code>couverture_hydraulique.pei.gros_debit</code>.
	 */
	public final TableField<Record, Boolean> GROS_DEBIT = createField("gros_debit", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>couverture_hydraulique.pei.type</code>.
	 */
	public final TableField<Record, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

	/**
	 * Create a <code>couverture_hydraulique.pei</code> table reference
	 */
	public Pei() {
		this("pei", null);
	}

	/**
	 * Create an aliased <code>couverture_hydraulique.pei</code> table reference
	 */
	public Pei(String alias) {
		this(alias, PEI);
	}

	private Pei(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Pei(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, CouvertureHydraulique.COUVERTURE_HYDRAULIQUE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Integer> getIdentity() {
		return Keys.IDENTITY_PEI;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.PEI_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.PEI_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Pei as(String alias) {
		return new Pei(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Pei rename(String name) {
		return new Pei(name, null);
	}
}
