/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.couverture_hydraulique.tables;


import com.vividsolutions.jts.geom.Geometry;

import fr.sdis83.remocra.db.converter.GeometryBinding;
import fr.sdis83.remocra.db.model.couverture_hydraulique.CouvertureHydraulique;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TempDistances extends TableImpl<Record> {

	private static final long serialVersionUID = -827933907;

	/**
	 * The reference instance of <code>couverture_hydraulique.temp_distances</code>
	 */
	public static final TempDistances TEMP_DISTANCES = new TempDistances();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>couverture_hydraulique.temp_distances.sommet</code>.
	 */
	public final TableField<Record, Integer> SOMMET = createField("sommet", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>couverture_hydraulique.temp_distances.voie</code>.
	 */
	public final TableField<Record, Integer> VOIE = createField("voie", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>couverture_hydraulique.temp_distances.distance</code>.
	 */
	public final TableField<Record, Double> DISTANCE = createField("distance", org.jooq.impl.SQLDataType.DOUBLE, this, "");

	/**
	 * The column <code>couverture_hydraulique.temp_distances.geometrie</code>.
	 */
	public final TableField<Record, Geometry> GEOMETRIE = createField("geometrie", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"), this, "", new GeometryBinding());

	/**
	 * The column <code>couverture_hydraulique.temp_distances.side</code>.
	 */
	public final TableField<Record, String> SIDE = createField("side", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>couverture_hydraulique.temp_distances.traversable</code>.
	 */
	public final TableField<Record, Boolean> TRAVERSABLE = createField("traversable", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>couverture_hydraulique.temp_distances.voieprecedente</code>.
	 */
	public final TableField<Record, Integer> VOIEPRECEDENTE = createField("voieprecedente", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>couverture_hydraulique.temp_distances.start</code>.
	 */
	public final TableField<Record, Integer> START = createField("start", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>couverture_hydraulique.temp_distances</code> table reference
	 */
	public TempDistances() {
		this("temp_distances", null);
	}

	/**
	 * Create an aliased <code>couverture_hydraulique.temp_distances</code> table reference
	 */
	public TempDistances(String alias) {
		this(alias, TEMP_DISTANCES);
	}

	private TempDistances(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private TempDistances(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, CouvertureHydraulique.COUVERTURE_HYDRAULIQUE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TempDistances as(String alias) {
		return new TempDistances(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TempDistances rename(String name) {
		return new TempDistances(name, null);
	}
}
