/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.pdi.tables;


import fr.sdis83.remocra.db.model.pdi.Pdi;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VueZoneCompetence extends TableImpl<Record> {

	private static final long serialVersionUID = 960277880;

	/**
	 * The reference instance of <code>pdi.vue_zone_competence</code>
	 */
	public static final VueZoneCompetence VUE_ZONE_COMPETENCE = new VueZoneCompetence();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>pdi.vue_zone_competence.id</code>.
	 */
	public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>pdi.vue_zone_competence.libelle</code>.
	 */
	public final TableField<Record, String> LIBELLE = createField("libelle", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>pdi.vue_zone_competence</code> table reference
	 */
	public VueZoneCompetence() {
		this("vue_zone_competence", null);
	}

	/**
	 * Create an aliased <code>pdi.vue_zone_competence</code> table reference
	 */
	public VueZoneCompetence(String alias) {
		this(alias, VUE_ZONE_COMPETENCE);
	}

	private VueZoneCompetence(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private VueZoneCompetence(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Pdi.PDI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public VueZoneCompetence as(String alias) {
		return new VueZoneCompetence(alias, this);
	}

	/**
	 * Rename this table
	 */
	public VueZoneCompetence rename(String name) {
		return new VueZoneCompetence(name, null);
	}
}
