/*
 * This file is generated by jOOQ.
 */
package fr.sdis83.remocra.db.model.incoming.tables;


import fr.sdis83.remocra.db.model.incoming.Incoming;
import fr.sdis83.remocra.db.model.incoming.Indexes;
import fr.sdis83.remocra.db.model.incoming.Keys;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tournee extends TableImpl<Record> {

    private static final long serialVersionUID = 1143144154;

    /**
     * The reference instance of <code>incoming.tournee</code>
     */
    public static final Tournee TOURNEE = new Tournee();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>incoming.tournee.id_tournee_remocra</code>.
     */
    public final TableField<Record, Long> ID_TOURNEE_REMOCRA = createField("id_tournee_remocra", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>incoming.tournee.nom_tournee</code>.
     */
    public final TableField<Record, String> NOM_TOURNEE = createField("nom_tournee", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>incoming.tournee</code> table reference
     */
    public Tournee() {
        this(DSL.name("tournee"), null);
    }

    /**
     * Create an aliased <code>incoming.tournee</code> table reference
     */
    public Tournee(String alias) {
        this(DSL.name(alias), TOURNEE);
    }

    /**
     * Create an aliased <code>incoming.tournee</code> table reference
     */
    public Tournee(Name alias) {
        this(alias, TOURNEE);
    }

    private Tournee(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Tournee(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Tournee(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, TOURNEE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Incoming.INCOMING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TOURNEE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.TOURNEE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.TOURNEE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.TOURNEE__TOURNEE_ID_TOURNEE_REMOCRA_FKEY);
    }

    public fr.sdis83.remocra.db.model.remocra.tables.Tournee tournee() {
        return new fr.sdis83.remocra.db.model.remocra.tables.Tournee(this, Keys.TOURNEE__TOURNEE_ID_TOURNEE_REMOCRA_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tournee as(String alias) {
        return new Tournee(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Tournee as(Name alias) {
        return new Tournee(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tournee rename(String name) {
        return new Tournee(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tournee rename(Name name) {
        return new Tournee(name, null);
    }
}
