/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.tracabilite.routines;


import fr.sdis83.remocra.db.model.tracabilite.Tracabilite;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrgHydrant extends AbstractRoutine<Object> {

	private static final long serialVersionUID = 1320519818;

	/**
	 * The parameter <code>tracabilite.trg_hydrant.RETURN_VALUE</code>.
	 */
	public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"), false);

	/**
	 * Create a new routine call instance
	 */
	public TrgHydrant() {
		super("trg_hydrant", Tracabilite.TRACABILITE, org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"));

		setReturnParameter(RETURN_VALUE);
	}
}
