/*
 * This file is generated by jOOQ.
 */
package fr.sdis83.remocra.db.model.remocra.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Modèle de courrier reférencant un fichier OTT et permettant la génération 
 * d'un courrier au format ODT
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourrierModele implements Serializable {

    private static final long serialVersionUID = -899134909;

    private Long   id;
    private String code;
    private String libelle;
    private String description;
    private String modeleOtt;
    private String sourceXml;
    private String messageObjet;
    private String messageCorps;
    private Long   thematique;

    public CourrierModele() {}

    public CourrierModele(CourrierModele value) {
        this.id = value.id;
        this.code = value.code;
        this.libelle = value.libelle;
        this.description = value.description;
        this.modeleOtt = value.modeleOtt;
        this.sourceXml = value.sourceXml;
        this.messageObjet = value.messageObjet;
        this.messageCorps = value.messageCorps;
        this.thematique = value.thematique;
    }

    public CourrierModele(
        Long   id,
        String code,
        String libelle,
        String description,
        String modeleOtt,
        String sourceXml,
        String messageObjet,
        String messageCorps,
        Long   thematique
    ) {
        this.id = id;
        this.code = code;
        this.libelle = libelle;
        this.description = description;
        this.modeleOtt = modeleOtt;
        this.sourceXml = sourceXml;
        this.messageObjet = messageObjet;
        this.messageCorps = messageCorps;
        this.thematique = thematique;
    }

    public Long getId() {
        return this.id;
    }

    public CourrierModele setId(Long id) {
        this.id = id;
        return this;
    }

    public String getCode() {
        return this.code;
    }

    public CourrierModele setCode(String code) {
        this.code = code;
        return this;
    }

    public String getLibelle() {
        return this.libelle;
    }

    public CourrierModele setLibelle(String libelle) {
        this.libelle = libelle;
        return this;
    }

    public String getDescription() {
        return this.description;
    }

    public CourrierModele setDescription(String description) {
        this.description = description;
        return this;
    }

    public String getModeleOtt() {
        return this.modeleOtt;
    }

    public CourrierModele setModeleOtt(String modeleOtt) {
        this.modeleOtt = modeleOtt;
        return this;
    }

    public String getSourceXml() {
        return this.sourceXml;
    }

    public CourrierModele setSourceXml(String sourceXml) {
        this.sourceXml = sourceXml;
        return this;
    }

    public String getMessageObjet() {
        return this.messageObjet;
    }

    public CourrierModele setMessageObjet(String messageObjet) {
        this.messageObjet = messageObjet;
        return this;
    }

    public String getMessageCorps() {
        return this.messageCorps;
    }

    public CourrierModele setMessageCorps(String messageCorps) {
        this.messageCorps = messageCorps;
        return this;
    }

    public Long getThematique() {
        return this.thematique;
    }

    public CourrierModele setThematique(Long thematique) {
        this.thematique = thematique;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CourrierModele (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(libelle);
        sb.append(", ").append(description);
        sb.append(", ").append(modeleOtt);
        sb.append(", ").append(sourceXml);
        sb.append(", ").append(messageObjet);
        sb.append(", ").append(messageCorps);
        sb.append(", ").append(thematique);

        sb.append(")");
        return sb.toString();
    }
}
