/*
 * This file is generated by jOOQ.
 */
package fr.sdis83.remocra.db.model.remocra.tables.pojos;


import java.io.Serializable;
import java.time.Instant;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Document implements Serializable {

    private static final long serialVersionUID = -1813645138;

    private Long    id;
    private String  code;
    private Instant date;
    private String  fichier;
    private String  repertoire;
    private String  type;
    private Instant dateDoc;

    public Document() {}

    public Document(Document value) {
        this.id = value.id;
        this.code = value.code;
        this.date = value.date;
        this.fichier = value.fichier;
        this.repertoire = value.repertoire;
        this.type = value.type;
        this.dateDoc = value.dateDoc;
    }

    public Document(
        Long    id,
        String  code,
        Instant date,
        String  fichier,
        String  repertoire,
        String  type,
        Instant dateDoc
    ) {
        this.id = id;
        this.code = code;
        this.date = date;
        this.fichier = fichier;
        this.repertoire = repertoire;
        this.type = type;
        this.dateDoc = dateDoc;
    }

    public Long getId() {
        return this.id;
    }

    public Document setId(Long id) {
        this.id = id;
        return this;
    }

    public String getCode() {
        return this.code;
    }

    public Document setCode(String code) {
        this.code = code;
        return this;
    }

    public Instant getDate() {
        return this.date;
    }

    public Document setDate(Instant date) {
        this.date = date;
        return this;
    }

    public String getFichier() {
        return this.fichier;
    }

    public Document setFichier(String fichier) {
        this.fichier = fichier;
        return this;
    }

    public String getRepertoire() {
        return this.repertoire;
    }

    public Document setRepertoire(String repertoire) {
        this.repertoire = repertoire;
        return this;
    }

    public String getType() {
        return this.type;
    }

    public Document setType(String type) {
        this.type = type;
        return this;
    }

    public Instant getDateDoc() {
        return this.dateDoc;
    }

    public Document setDateDoc(Instant dateDoc) {
        this.dateDoc = dateDoc;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Document (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(date);
        sb.append(", ").append(fichier);
        sb.append(", ").append(repertoire);
        sb.append(", ").append(type);
        sb.append(", ").append(dateDoc);

        sb.append(")");
        return sb.toString();
    }
}
