/*
 * This file is generated by jOOQ.
 */
package fr.sdis83.remocra.db.model.remocra.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Site de PEI
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GestionnaireSite implements Serializable {

    private static final long serialVersionUID = 591892147;

    private Long    id;
    private Boolean actif;
    private String  code;
    private String  nom;
    private Object  geometrie;
    private Long    idGestionnaire;

    public GestionnaireSite() {}

    public GestionnaireSite(GestionnaireSite value) {
        this.id = value.id;
        this.actif = value.actif;
        this.code = value.code;
        this.nom = value.nom;
        this.geometrie = value.geometrie;
        this.idGestionnaire = value.idGestionnaire;
    }

    public GestionnaireSite(
        Long    id,
        Boolean actif,
        String  code,
        String  nom,
        Object  geometrie,
        Long    idGestionnaire
    ) {
        this.id = id;
        this.actif = actif;
        this.code = code;
        this.nom = nom;
        this.geometrie = geometrie;
        this.idGestionnaire = idGestionnaire;
    }

    public Long getId() {
        return this.id;
    }

    public GestionnaireSite setId(Long id) {
        this.id = id;
        return this;
    }

    public Boolean getActif() {
        return this.actif;
    }

    public GestionnaireSite setActif(Boolean actif) {
        this.actif = actif;
        return this;
    }

    public String getCode() {
        return this.code;
    }

    public GestionnaireSite setCode(String code) {
        this.code = code;
        return this;
    }

    public String getNom() {
        return this.nom;
    }

    public GestionnaireSite setNom(String nom) {
        this.nom = nom;
        return this;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getGeometrie() {
        return this.geometrie;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public GestionnaireSite setGeometrie(Object geometrie) {
        this.geometrie = geometrie;
        return this;
    }

    public Long getIdGestionnaire() {
        return this.idGestionnaire;
    }

    public GestionnaireSite setIdGestionnaire(Long idGestionnaire) {
        this.idGestionnaire = idGestionnaire;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GestionnaireSite (");

        sb.append(id);
        sb.append(", ").append(actif);
        sb.append(", ").append(code);
        sb.append(", ").append(nom);
        sb.append(", ").append(geometrie);
        sb.append(", ").append(idGestionnaire);

        sb.append(")");
        return sb.toString();
    }
}
