/*
 * This file is generated by jOOQ.
 */
package fr.sdis83.remocra.db.model.remocra.tables.pojos;


import java.io.Serializable;
import java.time.Instant;

import javax.annotation.Generated;


/**
 * Suite donnée à une visite liée à une obligation légale de débroussaillement
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OldebVisiteSuite implements Serializable {

    private static final long serialVersionUID = -937205833;

    private Long    id;
    private Long    visite;
    private Long    suite;
    private Instant dateSuite;
    private String  observation;

    public OldebVisiteSuite() {}

    public OldebVisiteSuite(OldebVisiteSuite value) {
        this.id = value.id;
        this.visite = value.visite;
        this.suite = value.suite;
        this.dateSuite = value.dateSuite;
        this.observation = value.observation;
    }

    public OldebVisiteSuite(
        Long    id,
        Long    visite,
        Long    suite,
        Instant dateSuite,
        String  observation
    ) {
        this.id = id;
        this.visite = visite;
        this.suite = suite;
        this.dateSuite = dateSuite;
        this.observation = observation;
    }

    public Long getId() {
        return this.id;
    }

    public OldebVisiteSuite setId(Long id) {
        this.id = id;
        return this;
    }

    public Long getVisite() {
        return this.visite;
    }

    public OldebVisiteSuite setVisite(Long visite) {
        this.visite = visite;
        return this;
    }

    public Long getSuite() {
        return this.suite;
    }

    public OldebVisiteSuite setSuite(Long suite) {
        this.suite = suite;
        return this;
    }

    public Instant getDateSuite() {
        return this.dateSuite;
    }

    public OldebVisiteSuite setDateSuite(Instant dateSuite) {
        this.dateSuite = dateSuite;
        return this;
    }

    public String getObservation() {
        return this.observation;
    }

    public OldebVisiteSuite setObservation(String observation) {
        this.observation = observation;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OldebVisiteSuite (");

        sb.append(id);
        sb.append(", ").append(visite);
        sb.append(", ").append(suite);
        sb.append(", ").append(dateSuite);
        sb.append(", ").append(observation);

        sb.append(")");
        return sb.toString();
    }
}
