/*
 * This file is generated by jOOQ.
 */
package fr.sdis83.remocra.db.model.remocra.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Planification d'un processus ETL. Une demande de processus est automatiquement 
 * créée par le planificateur
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessusEtlPlanification implements Serializable {

    private static final long serialVersionUID = -632797866;

    private Long   id;
    private Long   modele;
    private String expression;
    private String categorie;
    private Long   objetConcerne;

    public ProcessusEtlPlanification() {}

    public ProcessusEtlPlanification(ProcessusEtlPlanification value) {
        this.id = value.id;
        this.modele = value.modele;
        this.expression = value.expression;
        this.categorie = value.categorie;
        this.objetConcerne = value.objetConcerne;
    }

    public ProcessusEtlPlanification(
        Long   id,
        Long   modele,
        String expression,
        String categorie,
        Long   objetConcerne
    ) {
        this.id = id;
        this.modele = modele;
        this.expression = expression;
        this.categorie = categorie;
        this.objetConcerne = objetConcerne;
    }

    public Long getId() {
        return this.id;
    }

    public ProcessusEtlPlanification setId(Long id) {
        this.id = id;
        return this;
    }

    public Long getModele() {
        return this.modele;
    }

    public ProcessusEtlPlanification setModele(Long modele) {
        this.modele = modele;
        return this;
    }

    public String getExpression() {
        return this.expression;
    }

    public ProcessusEtlPlanification setExpression(String expression) {
        this.expression = expression;
        return this;
    }

    public String getCategorie() {
        return this.categorie;
    }

    public ProcessusEtlPlanification setCategorie(String categorie) {
        this.categorie = categorie;
        return this;
    }

    public Long getObjetConcerne() {
        return this.objetConcerne;
    }

    public ProcessusEtlPlanification setObjetConcerne(Long objetConcerne) {
        this.objetConcerne = objetConcerne;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProcessusEtlPlanification (");

        sb.append(id);
        sb.append(", ").append(modele);
        sb.append(", ").append(expression);
        sb.append(", ").append(categorie);
        sb.append(", ").append(objetConcerne);

        sb.append(")");
        return sb.toString();
    }
}
