/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra.enums;


import fr.sdis83.remocra.db.model.remocra.Remocra;

import javax.annotation.Generated;

import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum TypeCategorieParametre implements EnumType {

	MOBILE("MOBILE"),

	GENERAL("GENERAL");

	private final String literal;

	private TypeCategorieParametre(String literal) {
		this.literal = literal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Schema getSchema() {
		return Remocra.REMOCRA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getName() {
		return "type_categorie_parametre";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getLiteral() {
		return literal;
	}
}
