/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra;


import fr.sdis83.remocra.db.model.remocra.Remocra;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in remocra
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>remocra.alerte_document_id_seq</code>
	 */
	public static final Sequence<Long> ALERTE_DOCUMENT_ID_SEQ = new SequenceImpl<Long>("alerte_document_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.alerte_elt_ano_id_seq</code>
	 */
	public static final Sequence<Long> ALERTE_ELT_ANO_ID_SEQ = new SequenceImpl<Long>("alerte_elt_ano_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.alerte_elt_id_seq</code>
	 */
	public static final Sequence<Long> ALERTE_ELT_ID_SEQ = new SequenceImpl<Long>("alerte_elt_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.alerte_id_seq</code>
	 */
	public static final Sequence<Long> ALERTE_ID_SEQ = new SequenceImpl<Long>("alerte_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.bloc_document_id_seq</code>
	 */
	public static final Sequence<Long> BLOC_DOCUMENT_ID_SEQ = new SequenceImpl<Long>("bloc_document_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.cadastre_parcelle_id_seq</code>
	 */
	public static final Sequence<Long> CADASTRE_PARCELLE_ID_SEQ = new SequenceImpl<Long>("cadastre_parcelle_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.cadastre_section_id_seq</code>
	 */
	public static final Sequence<Long> CADASTRE_SECTION_ID_SEQ = new SequenceImpl<Long>("cadastre_section_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.commune_id_seq</code>
	 */
	public static final Sequence<Long> COMMUNE_ID_SEQ = new SequenceImpl<Long>("commune_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.courrier_document_id_seq</code>
	 */
	public static final Sequence<Long> COURRIER_DOCUMENT_ID_SEQ = new SequenceImpl<Long>("courrier_document_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.courrier_modele_id_seq</code>
	 */
	public static final Sequence<Long> COURRIER_MODELE_ID_SEQ = new SequenceImpl<Long>("courrier_modele_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.crise_document_id_seq</code>
	 */
	public static final Sequence<Long> CRISE_DOCUMENT_ID_SEQ = new SequenceImpl<Long>("crise_document_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.crise_evenement_complement_id_seq</code>
	 */
	public static final Sequence<Long> CRISE_EVENEMENT_COMPLEMENT_ID_SEQ = new SequenceImpl<Long>("crise_evenement_complement_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.crise_evenement_id_seq</code>
	 */
	public static final Sequence<Long> CRISE_EVENEMENT_ID_SEQ = new SequenceImpl<Long>("crise_evenement_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.crise_id_seq</code>
	 */
	public static final Sequence<Long> CRISE_ID_SEQ = new SequenceImpl<Long>("crise_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.crise_suivi_id_seq</code>
	 */
	public static final Sequence<Long> CRISE_SUIVI_ID_SEQ = new SequenceImpl<Long>("crise_suivi_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.crise_suivi_message_modele_id_seq</code>
	 */
	public static final Sequence<Long> CRISE_SUIVI_MESSAGE_MODELE_ID_SEQ = new SequenceImpl<Long>("crise_suivi_message_modele_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.dde_mdp_id_seq</code>
	 */
	public static final Sequence<Long> DDE_MDP_ID_SEQ = new SequenceImpl<Long>("dde_mdp_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.depot_document_id_seq</code>
	 */
	public static final Sequence<Long> DEPOT_DOCUMENT_ID_SEQ = new SequenceImpl<Long>("depot_document_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.document_id_seq</code>
	 */
	public static final Sequence<Long> DOCUMENT_ID_SEQ = new SequenceImpl<Long>("document_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.droit_id_seq</code>
	 */
	public static final Sequence<Long> DROIT_ID_SEQ = new SequenceImpl<Long>("droit_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.email_id_seq</code>
	 */
	public static final Sequence<Long> EMAIL_ID_SEQ = new SequenceImpl<Long>("email_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.email_modele_id_seq</code>
	 */
	public static final Sequence<Long> EMAIL_MODELE_ID_SEQ = new SequenceImpl<Long>("email_modele_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.export_modele_id_seq</code>
	 */
	public static final Sequence<Long> EXPORT_MODELE_ID_SEQ = new SequenceImpl<Long>("export_modele_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.hibernate_sequence</code>
	 */
	public static final Sequence<Long> HIBERNATE_SEQUENCE = new SequenceImpl<Long>("hibernate_sequence", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.hydrant_document_id_seq</code>
	 */
	public static final Sequence<Long> HYDRANT_DOCUMENT_ID_SEQ = new SequenceImpl<Long>("hydrant_document_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.hydrant_id_seq</code>
	 */
	public static final Sequence<Long> HYDRANT_ID_SEQ = new SequenceImpl<Long>("hydrant_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.hydrant_indispo_temporaire_id_seq</code>
	 */
	public static final Sequence<Long> HYDRANT_INDISPO_TEMPORAIRE_ID_SEQ = new SequenceImpl<Long>("hydrant_indispo_temporaire_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.hydrant_prescrit_id_seq</code>
	 */
	public static final Sequence<Long> HYDRANT_PRESCRIT_ID_SEQ = new SequenceImpl<Long>("hydrant_prescrit_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.hydrant_tournees_id_seq</code>
	 */
	public static final Sequence<Long> HYDRANT_TOURNEES_ID_SEQ = new SequenceImpl<Long>("hydrant_tournees_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.metadonnee_id_seq</code>
	 */
	public static final Sequence<Long> METADONNEE_ID_SEQ = new SequenceImpl<Long>("metadonnee_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.ogc_couche_id_seq</code>
	 */
	public static final Sequence<Long> OGC_COUCHE_ID_SEQ = new SequenceImpl<Long>("ogc_couche_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.ogc_service_id_seq</code>
	 */
	public static final Sequence<Long> OGC_SERVICE_ID_SEQ = new SequenceImpl<Long>("ogc_service_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.ogc_source_id_seq</code>
	 */
	public static final Sequence<Long> OGC_SOURCE_ID_SEQ = new SequenceImpl<Long>("ogc_source_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.oldeb_id_seq</code>
	 */
	public static final Sequence<Long> OLDEB_ID_SEQ = new SequenceImpl<Long>("oldeb_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.oldeb_locataire_id_seq</code>
	 */
	public static final Sequence<Long> OLDEB_LOCATAIRE_ID_SEQ = new SequenceImpl<Long>("oldeb_locataire_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.oldeb_proprietaire_id_seq</code>
	 */
	public static final Sequence<Long> OLDEB_PROPRIETAIRE_ID_SEQ = new SequenceImpl<Long>("oldeb_proprietaire_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.oldeb_propriete_id_seq</code>
	 */
	public static final Sequence<Long> OLDEB_PROPRIETE_ID_SEQ = new SequenceImpl<Long>("oldeb_propriete_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.oldeb_visite_document_id_seq</code>
	 */
	public static final Sequence<Long> OLDEB_VISITE_DOCUMENT_ID_SEQ = new SequenceImpl<Long>("oldeb_visite_document_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.oldeb_visite_id_seq</code>
	 */
	public static final Sequence<Long> OLDEB_VISITE_ID_SEQ = new SequenceImpl<Long>("oldeb_visite_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.oldeb_visite_suite_id_seq</code>
	 */
	public static final Sequence<Long> OLDEB_VISITE_SUITE_ID_SEQ = new SequenceImpl<Long>("oldeb_visite_suite_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.organisme_id_seq</code>
	 */
	public static final Sequence<Long> ORGANISME_ID_SEQ = new SequenceImpl<Long>("organisme_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.permis_document_id_seq</code>
	 */
	public static final Sequence<Long> PERMIS_DOCUMENT_ID_SEQ = new SequenceImpl<Long>("permis_document_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.permis_id_seq</code>
	 */
	public static final Sequence<Long> PERMIS_ID_SEQ = new SequenceImpl<Long>("permis_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.processus_etl_document_id_seq</code>
	 */
	public static final Sequence<Long> PROCESSUS_ETL_DOCUMENT_ID_SEQ = new SequenceImpl<Long>("processus_etl_document_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.processus_etl_id_seq</code>
	 */
	public static final Sequence<Long> PROCESSUS_ETL_ID_SEQ = new SequenceImpl<Long>("processus_etl_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.processus_etl_modele_id_seq</code>
	 */
	public static final Sequence<Long> PROCESSUS_ETL_MODELE_ID_SEQ = new SequenceImpl<Long>("processus_etl_modele_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.processus_etl_modele_parametre_id_seq</code>
	 */
	public static final Sequence<Long> PROCESSUS_ETL_MODELE_PARAMETRE_ID_SEQ = new SequenceImpl<Long>("processus_etl_modele_parametre_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.processus_etl_planification_id_seq</code>
	 */
	public static final Sequence<Long> PROCESSUS_ETL_PLANIFICATION_ID_SEQ = new SequenceImpl<Long>("processus_etl_planification_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.processus_etl_statut_id_seq</code>
	 */
	public static final Sequence<Long> PROCESSUS_ETL_STATUT_ID_SEQ = new SequenceImpl<Long>("processus_etl_statut_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.profil_droit_id_seq</code>
	 */
	public static final Sequence<Long> PROFIL_DROIT_ID_SEQ = new SequenceImpl<Long>("profil_droit_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.profil_organisme_id_seq</code>
	 */
	public static final Sequence<Long> PROFIL_ORGANISME_ID_SEQ = new SequenceImpl<Long>("profil_organisme_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.profil_organisme_utilisateur_droit_id_seq</code>
	 */
	public static final Sequence<Long> PROFIL_ORGANISME_UTILISATEUR_DROIT_ID_SEQ = new SequenceImpl<Long>("profil_organisme_utilisateur_droit_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.profil_utilisateur_id_seq</code>
	 */
	public static final Sequence<Long> PROFIL_UTILISATEUR_ID_SEQ = new SequenceImpl<Long>("profil_utilisateur_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.rci_document_id_seq</code>
	 */
	public static final Sequence<Long> RCI_DOCUMENT_ID_SEQ = new SequenceImpl<Long>("rci_document_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.rci_id_seq</code>
	 */
	public static final Sequence<Long> RCI_ID_SEQ = new SequenceImpl<Long>("rci_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.repertoire_lieu_id_seq</code>
	 */
	public static final Sequence<Long> REPERTOIRE_LIEU_ID_SEQ = new SequenceImpl<Long>("repertoire_lieu_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.requete_modele_id_seq</code>
	 */
	public static final Sequence<Long> REQUETE_MODELE_ID_SEQ = new SequenceImpl<Long>("requete_modele_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.requete_modele_parametre_id_seq</code>
	 */
	public static final Sequence<Long> REQUETE_MODELE_PARAMETRE_ID_SEQ = new SequenceImpl<Long>("requete_modele_parametre_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.requete_modele_selection_detail_id_seq</code>
	 */
	public static final Sequence<Long> REQUETE_MODELE_SELECTION_DETAIL_ID_SEQ = new SequenceImpl<Long>("requete_modele_selection_detail_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.requete_modele_selection_id_seq</code>
	 */
	public static final Sequence<Long> REQUETE_MODELE_SELECTION_ID_SEQ = new SequenceImpl<Long>("requete_modele_selection_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.sous_type_alerte_elt_id_seq</code>
	 */
	public static final Sequence<Long> SOUS_TYPE_ALERTE_ELT_ID_SEQ = new SequenceImpl<Long>("sous_type_alerte_elt_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.synchronisation_id_seq</code>
	 */
	public static final Sequence<Long> SYNCHRONISATION_ID_SEQ = new SequenceImpl<Long>("synchronisation_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.thematique_id_seq</code>
	 */
	public static final Sequence<Long> THEMATIQUE_ID_SEQ = new SequenceImpl<Long>("thematique_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.tournee_id_seq</code>
	 */
	public static final Sequence<Long> TOURNEE_ID_SEQ = new SequenceImpl<Long>("tournee_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_alerte_ano_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_ALERTE_ANO_ID_SEQ = new SequenceImpl<Long>("type_alerte_ano_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_alerte_elt_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_ALERTE_ELT_ID_SEQ = new SequenceImpl<Long>("type_alerte_elt_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_crise_categorie_evenement_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_CRISE_CATEGORIE_EVENEMENT_ID_SEQ = new SequenceImpl<Long>("type_crise_categorie_evenement_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_crise_contexte_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_CRISE_CONTEXTE_ID_SEQ = new SequenceImpl<Long>("type_crise_contexte_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_crise_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_CRISE_ID_SEQ = new SequenceImpl<Long>("type_crise_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_crise_nature_evenement_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_CRISE_NATURE_EVENEMENT_ID_SEQ = new SequenceImpl<Long>("type_crise_nature_evenement_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_crise_propriete_evenement_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_CRISE_PROPRIETE_EVENEMENT_ID_SEQ = new SequenceImpl<Long>("type_crise_propriete_evenement_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_crise_statut_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_CRISE_STATUT_ID_SEQ = new SequenceImpl<Long>("type_crise_statut_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_droit_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_DROIT_ID_SEQ = new SequenceImpl<Long>("type_droit_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_hydrant_anomalie_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_HYDRANT_ANOMALIE_ID_SEQ = new SequenceImpl<Long>("type_hydrant_anomalie_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_hydrant_anomalie_nature_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_HYDRANT_ANOMALIE_NATURE_ID_SEQ = new SequenceImpl<Long>("type_hydrant_anomalie_nature_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_hydrant_critere_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_HYDRANT_CRITERE_ID_SEQ = new SequenceImpl<Long>("type_hydrant_critere_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_hydrant_diametre_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_HYDRANT_DIAMETRE_ID_SEQ = new SequenceImpl<Long>("type_hydrant_diametre_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_hydrant_domaine_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_HYDRANT_DOMAINE_ID_SEQ = new SequenceImpl<Long>("type_hydrant_domaine_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_hydrant_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_HYDRANT_ID_SEQ = new SequenceImpl<Long>("type_hydrant_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_hydrant_indispo_statut_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_HYDRANT_INDISPO_STATUT_ID_SEQ = new SequenceImpl<Long>("type_hydrant_indispo_statut_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_hydrant_marque_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_HYDRANT_MARQUE_ID_SEQ = new SequenceImpl<Long>("type_hydrant_marque_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_hydrant_materiau_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_HYDRANT_MATERIAU_ID_SEQ = new SequenceImpl<Long>("type_hydrant_materiau_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_hydrant_modele_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_HYDRANT_MODELE_ID_SEQ = new SequenceImpl<Long>("type_hydrant_modele_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_hydrant_nature_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_HYDRANT_NATURE_ID_SEQ = new SequenceImpl<Long>("type_hydrant_nature_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_hydrant_positionnement_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_HYDRANT_POSITIONNEMENT_ID_SEQ = new SequenceImpl<Long>("type_hydrant_positionnement_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_hydrant_saisie_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_HYDRANT_SAISIE_ID_SEQ = new SequenceImpl<Long>("type_hydrant_saisie_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_hydrant_vol_constate_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_HYDRANT_VOL_CONSTATE_ID_SEQ = new SequenceImpl<Long>("type_hydrant_vol_constate_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_oldeb_acces_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_OLDEB_ACCES_ID_SEQ = new SequenceImpl<Long>("type_oldeb_acces_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_oldeb_action_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_OLDEB_ACTION_ID_SEQ = new SequenceImpl<Long>("type_oldeb_action_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_oldeb_anomalie_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_OLDEB_ANOMALIE_ID_SEQ = new SequenceImpl<Long>("type_oldeb_anomalie_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_oldeb_avis_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_OLDEB_AVIS_ID_SEQ = new SequenceImpl<Long>("type_oldeb_avis_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_oldeb_caracteristique_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_OLDEB_CARACTERISTIQUE_ID_SEQ = new SequenceImpl<Long>("type_oldeb_caracteristique_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_oldeb_categorie_anomalie_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_OLDEB_CATEGORIE_ANOMALIE_ID_SEQ = new SequenceImpl<Long>("type_oldeb_categorie_anomalie_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_oldeb_categorie_caracteristique_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_OLDEB_CATEGORIE_CARACTERISTIQUE_ID_SEQ = new SequenceImpl<Long>("type_oldeb_categorie_caracteristique_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_oldeb_debroussaillement_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_OLDEB_DEBROUSSAILLEMENT_ID_SEQ = new SequenceImpl<Long>("type_oldeb_debroussaillement_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_oldeb_residence_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_OLDEB_RESIDENCE_ID_SEQ = new SequenceImpl<Long>("type_oldeb_residence_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_oldeb_suite_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_OLDEB_SUITE_ID_SEQ = new SequenceImpl<Long>("type_oldeb_suite_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_oldeb_zone_urbanisme_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_OLDEB_ZONE_URBANISME_ID_SEQ = new SequenceImpl<Long>("type_oldeb_zone_urbanisme_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_organisme_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_ORGANISME_ID_SEQ = new SequenceImpl<Long>("type_organisme_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_permis_avis_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_PERMIS_AVIS_ID_SEQ = new SequenceImpl<Long>("type_permis_avis_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_permis_interservice_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_PERMIS_INTERSERVICE_ID_SEQ = new SequenceImpl<Long>("type_permis_interservice_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_rci_degre_certitude_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_RCI_DEGRE_CERTITUDE_ID_SEQ = new SequenceImpl<Long>("type_rci_degre_certitude_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_rci_origine_alerte_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_RCI_ORIGINE_ALERTE_ID_SEQ = new SequenceImpl<Long>("type_rci_origine_alerte_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_rci_prom_categorie_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_RCI_PROM_CATEGORIE_ID_SEQ = new SequenceImpl<Long>("type_rci_prom_categorie_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_rci_prom_famille_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_RCI_PROM_FAMILLE_ID_SEQ = new SequenceImpl<Long>("type_rci_prom_famille_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.type_rci_prom_partition_id_seq</code>
	 */
	public static final Sequence<Long> TYPE_RCI_PROM_PARTITION_ID_SEQ = new SequenceImpl<Long>("type_rci_prom_partition_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.utilisateur_id_seq</code>
	 */
	public static final Sequence<Long> UTILISATEUR_ID_SEQ = new SequenceImpl<Long>("utilisateur_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.voie_id_seq</code>
	 */
	public static final Sequence<Long> VOIE_ID_SEQ = new SequenceImpl<Long>("voie_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.zone_competence_id_seq</code>
	 */
	public static final Sequence<Long> ZONE_COMPETENCE_ID_SEQ = new SequenceImpl<Long>("zone_competence_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>remocra.zone_speciale_id_seq</code>
	 */
	public static final Sequence<Long> ZONE_SPECIALE_ID_SEQ = new SequenceImpl<Long>("zone_speciale_id_seq", Remocra.REMOCRA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
