#!/bin/bash
set -e

# Redéfition des accès à la base de données remocra

# kettle.properties
KETTLE_PROPERTIES=/home/pdi/.kettle/kettle.properties
KETTLE_PROPERTIES_TMP=/tmp/kettle.properties
if [ -f "$KETTLE_PROPERTIES" ]; then
  [ -n "${POSTGRES_DB_HOSTNAME}" ] && sed "s/REMOCRA_POSTGIS_DATABASE_HOST.*/REMOCRA_POSTGIS_DATABASE_HOST = ${POSTGRES_DB_HOSTNAME}/g" ${KETTLE_PROPERTIES} > $KETTLE_PROPERTIES_TMP && cat $KETTLE_PROPERTIES_TMP > ${KETTLE_PROPERTIES} && rm $KETTLE_PROPERTIES_TMP
  [ -n "${POSTGRES_DB_USERNAME}" ] && sed "s/REMOCRA_POSTGIS_DATABASE_USER_NAME.*/REMOCRA_POSTGIS_DATABASE_USER_NAME = ${POSTGRES_DB_USERNAME}/g" ${KETTLE_PROPERTIES} > $KETTLE_PROPERTIES_TMP && cat $KETTLE_PROPERTIES_TMP > ${KETTLE_PROPERTIES} && rm $KETTLE_PROPERTIES_TMP
  [ -n "${POSTGRES_DB_PASSWORD}" ] && sed "s/REMOCRA_POSTGIS_DATABASE_USER_PASSWORD.*/REMOCRA_POSTGIS_DATABASE_USER_PASSWORD = ${POSTGRES_DB_PASSWORD}/g" ${KETTLE_PROPERTIES} > $KETTLE_PROPERTIES_TMP && cat $KETTLE_PROPERTIES_TMP > ${KETTLE_PROPERTIES} && rm $KETTLE_PROPERTIES_TMP
fi

# repositories.xml
REPOSITORIES_XML=/home/pdi/.kettle/repositories.xml
REPOSITORIES_XML_TMP=/tmp/repositories.xml
if [ -f "$REPOSITORIES_XML" ]; then
  [ -n "${POSTGRES_DB_HOSTNAME}" ] && sed "s/<server>.*<\/server>/<server>${POSTGRES_DB_HOSTNAME}<\/server>/g" ${REPOSITORIES_XML} > $REPOSITORIES_XML_TMP && cat $REPOSITORIES_XML_TMP > ${REPOSITORIES_XML} && rm $REPOSITORIES_XML_TMP
  [ -n "${POSTGRES_DB_USERNAME}" ] && sed "s/<username>.*<\/username>/<username>${POSTGRES_DB_USERNAME}<\/username>/g" ${REPOSITORIES_XML} > $REPOSITORIES_XML_TMP && cat $REPOSITORIES_XML_TMP > ${REPOSITORIES_XML} && rm $REPOSITORIES_XML_TMP
  [ -n "${POSTGRES_DB_PASSWORD}" ] && sed "s/<password>.*<\/password>/<password>${POSTGRES_DB_PASSWORD}<\/password>/g" ${REPOSITORIES_XML} > $REPOSITORIES_XML_TMP && cat $REPOSITORIES_XML_TMP > ${REPOSITORIES_XML} && rm $REPOSITORIES_XML_TMP
fi

exit 0