version: '3.3'

# Valeurs des variables par défaut dans .env

services:
  db: 
    container_name: remocra-db
    image: mdillon/postgis:11-alpine
    #user: "${REMOCRA_UID:-1000}:${REMOCRA_GID:-1000}"
    ports:
      - "5432:5432"
    volumes:
      - .docker/db/postgresql_data:/var/lib/postgresql/data
      - .docker/remocra/logs:/usr/local/tomcat/logs
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: remocra
      TZ: "Europe/Paris"
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=fr_FR --lc-collate=fr_FR.utf8 --lc-ctype=fr_FR.utf8
    healthcheck:
      test: "exit 0"
    networks:
      remocra:
        aliases:
          - ${POSTGRES_DB_HOSTNAME}

  geoserver:
    container_name: remocra-geoserver
    build: ./geoserver
    image: remocra-geoserver
    user: "${REMOCRA_UID:-1000}:${REMOCRA_GID:-1000}"
    ports:
      - "8090:8090"
    volumes:
      - .docker/var_remocra/geoserver_data:/var/remocra/geoserver_data
    environment:
      GEOSERVER_PORT: ${GEOSERVER_PORT}
      GEOSERVER_DATA_DIR: ${GEOSERVER_DATA_DIR}
      GEOWEBCACHE_CACHE_DIR: ${GEOWEBCACHE_CACHE_DIR}
      GEOSERVER_INITIAL_MEMORY: ${GEOSERVER_INITIAL_MEMORY}
      GEOSERVER_MAXIMUM_MEMORY: ${GEOSERVER_MAXIMUM_MEMORY}
      # Accès à la base de données remocra
      POSTGRES_DB_HOSTNAME: ${POSTGRES_DB_HOSTNAME}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      # Credentials GeoServer
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USERNAME}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
      # Paramètres supplémentaires JVM
      #JAVA_OPTS:
    depends_on:
      - db
    healthcheck:
      test: curl --fail -s http://localhost:8090/geoserver/web/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      remocra:
        aliases:
          - geoserver.sdisxx.fr

  remocra:
    container_name: remocra
    build: ./remocra
    image: remocra
    user: "${REMOCRA_UID:-1000}:${REMOCRA_GID:-1000}"
    ports:
      - "8080:8080"
    volumes:
      - .docker/var_remocra:/var/remocra
    environment:
      LANG: "fr_FR.UTF-8"
      REMOCRA_PORT: ${REMOCRA_PORT}
      REMOCRA_INITIAL_MEMORY: ${REMOCRA_INITIAL_MEMORY}
      REMOCRA_MAXIMUM_MEMORY: ${REMOCRA_MAXIMUM_MEMORY}
      REMOCRA_LOGFILE: ${REMOCRA_LOGFILE}
      # Accès à la base de données remocra
      POSTGRES_DB_HOSTNAME: ${POSTGRES_DB_HOSTNAME}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      REMOCRA_SESSION_MIN: ${REMOCRA_SESSION_MIN}
      # Paramètres supplémentaires JVM
      #JAVA_OPTS:
    depends_on:
      - db
    healthcheck:
      test: curl --fail -s http://localhost:8080/remocra/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      remocra:
        aliases:
          - remocra.sdisxx.fr
          
  api:
    container_name: remocra-api
    image: remocra-api
    user: "${REMOCRA_UID:-1000}:${REMOCRA_GID:-1000}"
    build:
      context: ../api-remocra/
      dockerfile: ./dist/Dockerfile-image
    volumes:
      - ../api-remocra/dist/example/log:/app/log
      - ../api-remocra/dist/example/config:/app/config
    environment:
      POSTGRES_DB_SERVERNAME: ${POSTGRES_DB_SERVERNAME:-localhost}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD} 
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      API_REMOCRA_HTTP_PORT: ${API_REMOCRA_HTTP_PORT}
    ports:
      - "8881:8881"
    depends_on:
      - db
    healthcheck:
      test: curl --fail -s http://localhost:8881/openapi/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      remocra:
        aliases:
          - api.sdisxx.fr

  jobs-4.4:
    container_name: remocra-pdi-4.4-dkron
    build: ./pdi-4.4-dkron
    image: remocra-pdi-4.4-dkron
    user: "${REMOCRA_UID:-1000}:${REMOCRA_GID:-1000}"
    ports:
      - "8060:8060"
    volumes:
      - .docker/var_remocra:/var/remocra
      - .docker/jobs-common/kettle.properties:/home/pdi/.kettle/kettle.properties
      - .docker/jobs-common/remocra.properties:/home/pdi/remocra.properties
      - .docker/jobs-4.4/.kettle/repositories.xml:/home/pdi/.kettle/repositories.xml
      - .docker/jobs-4.4/dkron_data:/dkron/dkron.data
    environment:
      # Accès à la base de données remocra
      POSTGRES_DB_HOSTNAME: ${POSTGRES_DB_HOSTNAME}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      # PDI
      PDI_INITIAL_MEMORY: ${PDI_44_INITIAL_MEMORY}
      PDI_MAXIMUM_MEMORY: ${PDI_44_MAXIMUM_MEMORY}
      PDI_MAXIMUM_PERMSIZE: ${PDI_44_MAXIMUM_PERMSIZE}
      # Agent dkron
      DKRON_JOIN: ${DKRON_44_JOIN}
      DKRON_NODE_NAME: ${DKRON_44_NODE_NAME}
      DKRON_TAG: ${DKRON_44_TAG}
      DKRON_RPC_PORT: ${DKRON_44_RPC_PORT}
      DKRON_BIND_ADDR: ${DKRON_44_BIND_ADDR}
      DKRON_HTTP_ADDR: ${DKRON_44_HTTP_ADDR}
      DKRON_LOGFILE: ${DKRON_44_LOGFILE}
      DKRON_LOG_LEVEL: ${DKRON_44_LOG_LEVEL}
    depends_on:
      - db
    healthcheck:
      test: curl --fail -s http://localhost:8060/dashboard/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      remocra:
        aliases:
          - jobs-44.sdisxx.fr

  jobs:
    container_name: remocra-pdi-dkron
    build: ./pdi-dkron
    image: remocra-pdi-dkron
    user: "${REMOCRA_UID:-1000}:${REMOCRA_GID:-1000}"
    ports:
      - "8070:8070"
    volumes:
      - .docker/var_remocra:/var/remocra
      - .docker/jobs-common/kettle.properties:/home/pdi/.kettle/kettle.properties
      - .docker/jobs-common/remocra.properties:/home/pdi/remocra.properties
      - .docker/jobs/dkron_data:/dkron/dkron.data
    environment:
      # Accès à la base de données remocra
      POSTGRES_DB_HOSTNAME: ${POSTGRES_DB_HOSTNAME}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      # PDI
      PDI_INITIAL_MEMORY: ${PDI_44_INITIAL_MEMORY}
      PDI_MAXIMUM_MEMORY: ${PDI_44_MAXIMUM_MEMORY}
      PDI_MAXIMUM_PERMSIZE: ${PDI_44_MAXIMUM_PERMSIZE}
      # Agent dkron
      DKRON_JOIN: ${DKRON_JOIN}
      DKRON_NODE_NAME: ${DKRON_NODE_NAME}
      DKRON_TAG: ${DKRON_TAG}
      DKRON_RPC_PORT: ${DKRON_RPC_PORT}
      DKRON_BIND_ADDR: ${DKRON_BIND_ADDR}
      DKRON_HTTP_ADDR: ${DKRON_HTTP_ADDR}
      DKRON_LOGFILE: ${DKRON_LOGFILE}
      DKRON_LOG_LEVEL: ${DKRON_LOG_LEVEL}
    depends_on:
      - db
      - jobs-4.4
    healthcheck:
      test: curl --fail -s http://localhost:8070/dashboard/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      remocra:
        aliases:
          - jobs.sdisxx.fr

networks:
  remocra:
