/*
 * This file is generated by jOOQ.
 */
package fr.sdis83.remocra.db.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Lien entre un propriétaire et une parcelle soumise à une obligation légale 
 * de débroussaillement
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OldebPropriete implements Serializable {

    private static final long serialVersionUID = 76801918;

    private Long id;
    private Long oldeb;
    private Long proprietaire;
    private Long residence;

    public OldebPropriete() {}

    public OldebPropriete(OldebPropriete value) {
        this.id = value.id;
        this.oldeb = value.oldeb;
        this.proprietaire = value.proprietaire;
        this.residence = value.residence;
    }

    public OldebPropriete(
        Long id,
        Long oldeb,
        Long proprietaire,
        Long residence
    ) {
        this.id = id;
        this.oldeb = oldeb;
        this.proprietaire = proprietaire;
        this.residence = residence;
    }

    public Long getId() {
        return this.id;
    }

    public OldebPropriete setId(Long id) {
        this.id = id;
        return this;
    }

    public Long getOldeb() {
        return this.oldeb;
    }

    public OldebPropriete setOldeb(Long oldeb) {
        this.oldeb = oldeb;
        return this;
    }

    public Long getProprietaire() {
        return this.proprietaire;
    }

    public OldebPropriete setProprietaire(Long proprietaire) {
        this.proprietaire = proprietaire;
        return this;
    }

    public Long getResidence() {
        return this.residence;
    }

    public OldebPropriete setResidence(Long residence) {
        this.residence = residence;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OldebPropriete (");

        sb.append(id);
        sb.append(", ").append(oldeb);
        sb.append(", ").append(proprietaire);
        sb.append(", ").append(residence);

        sb.append(")");
        return sb.toString();
    }
}
