/*
 * This file is generated by jOOQ.
 */
package fr.sdis83.remocra.db.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ZoneCompetence implements Serializable {

    private static final long serialVersionUID = 638196271;

    private Long   id;
    private String code;
    private Object geometrie;
    private String nom;

    public ZoneCompetence() {}

    public ZoneCompetence(ZoneCompetence value) {
        this.id = value.id;
        this.code = value.code;
        this.geometrie = value.geometrie;
        this.nom = value.nom;
    }

    public ZoneCompetence(
        Long   id,
        String code,
        Object geometrie,
        String nom
    ) {
        this.id = id;
        this.code = code;
        this.geometrie = geometrie;
        this.nom = nom;
    }

    public Long getId() {
        return this.id;
    }

    public ZoneCompetence setId(Long id) {
        this.id = id;
        return this;
    }

    public String getCode() {
        return this.code;
    }

    public ZoneCompetence setCode(String code) {
        this.code = code;
        return this;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getGeometrie() {
        return this.geometrie;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public ZoneCompetence setGeometrie(Object geometrie) {
        this.geometrie = geometrie;
        return this;
    }

    public String getNom() {
        return this.nom;
    }

    public ZoneCompetence setNom(String nom) {
        this.nom = nom;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ZoneCompetence (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(geometrie);
        sb.append(", ").append(nom);

        sb.append(")");
        return sb.toString();
    }
}
