/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.pg_temp_5;


import javax.annotation.Generated;

import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgTemp_5 extends SchemaImpl {

	private static final long serialVersionUID = -1758565968;

	/**
	 * The reference instance of <code>pg_temp_5</code>
	 */
	public static final PgTemp_5 PG_TEMP_5 = new PgTemp_5();

	/**
	 * No further instances allowed
	 */
	private PgTemp_5() {
		super("pg_temp_5");
	}
}
