= Synchronisation des utilisateurs de l'annuaire vers REMOCRA

Ce traitement permet d'intégrer les utilisateurs extraits de l'annuaire via un fichier au format CSV.
Le fichier sera généré une fois par jour et sera nommé selon le formalisme suivant : "utilisateurs-AAAA-MM-JJ.csv" où AAAA correspond à l'année, MM correspond au numéro de mois et JJ correspond au numéro de jour (Ex : utilisateurs-2019-01-09.csv).

Le traitement vérifie dans un premier temps la présence du fichier, si celui ci n'est pas présent, un email d'alerte est transmis à une adresse email qui sera configurée dans le fichier propriété.

+++<u>Le traitement effectuera les actions suivantes :</u>+++

- *Création d'un utilisateur* : Si l'utilisateur est présent dans le fichier CSV mais non présent dans REMOCRA
- *Mise à jour d'un utilisateur* : Si l'utilisateur est présent dans le fichier CSV et présent dans REMOCRA
- *Désactivation d'un utilisateur* : Si l'utilisateur est présent dans REMOCRA (et créé initialement à partir d'une source extérieure) mais non présent dans le fichier CSV

===== Configuration
Le fichier _"remocraXX.properties"_ doit contenir les informations suivantes :
[width="100%",options="header"]
|===================
| Paramètre | Description
| PDI_EMAIL_NOTIF_SYNCHRO_UTILISATEUR | Adresse mail ou code de profil des utilisateurs à notifier pour la synchro des utilisateurs Remocra _ex :_ `exemple@exemple.com`, `SDIS-ADM-APP`
|===================

====== Format du fichier csv

[width="50%" options="no-header" cols="<s,"]
|====================
|Type de fichier|Tabulaire CSV
|Encodage|UTF-8
|Séparateur de colonnes|,
|Encapsulation de valeurs|"
|Format de date |AAAA-MM-JJ
|====================

====== Structure du fichier csv

[width="100%",options="header"]
|====================
|Nom du champ|Type|Obligatoire|Description
|prenom|Texte|Oui|Prénom de l'utilisateur
|nom|Texte|Oui|Nom de l'utilisateur
|identifiant|Texte|Oui|Correspond à l'identifiant de connexion
|telephone|Texte||Numéro de téléphone
|email|Texte|Oui|Adresse mail de l'utilisateur
|code_profil|Texte|Oui|Code du profil (Doit correspondre au code présent dans REMOCRA).
|code_organisme|Texte|Oui|Code organisme (Doit correspondre au code présent dans REMOCRA)
|====================


===== Lancement et planification de la synchronisation
L'exécution automatique s'effectue en planifiant le lancement du fichier ```/var/remocra/pdi/traitements_sdis/bspp/import_utilisateur.sh``` avec l'utilisateur ```postgres```.
