/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra.tables;


import fr.sdis83.remocra.db.model.remocra.Keys;
import fr.sdis83.remocra.db.model.remocra.Remocra;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * Profil de droit autorisé pour générer un courrier
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourrierModeleDroit extends TableImpl<Record> {

	private static final long serialVersionUID = 1239939292;

	/**
	 * The reference instance of <code>remocra.courrier_modele_droit</code>
	 */
	public static final CourrierModeleDroit COURRIER_MODELE_DROIT = new CourrierModeleDroit();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>remocra.courrier_modele_droit.modele</code>. Identifiant du modèle de courrier
	 */
	public final TableField<Record, Long> MODELE = createField("modele", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "Identifiant du modèle de courrier");

	/**
	 * The column <code>remocra.courrier_modele_droit.profil_droit</code>. Identifiant du profil de droit autorisé
	 */
	public final TableField<Record, Long> PROFIL_DROIT = createField("profil_droit", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "Identifiant du profil de droit autorisé");

	/**
	 * Create a <code>remocra.courrier_modele_droit</code> table reference
	 */
	public CourrierModeleDroit() {
		this("courrier_modele_droit", null);
	}

	/**
	 * Create an aliased <code>remocra.courrier_modele_droit</code> table reference
	 */
	public CourrierModeleDroit(String alias) {
		this(alias, COURRIER_MODELE_DROIT);
	}

	private CourrierModeleDroit(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private CourrierModeleDroit(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Remocra.REMOCRA, aliased, parameters, "Profil de droit autorisé pour générer un courrier");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.COURRIER_MODELE_DROIT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.COURRIER_MODELE_DROIT_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.COURRIER_MODELE_DROIT__COURRIER_MODELE_DROIT_MODELE, Keys.COURRIER_MODELE_DROIT__COURRIER_MODELE_DROIT_PROFIL_DROIT);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CourrierModeleDroit as(String alias) {
		return new CourrierModeleDroit(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CourrierModeleDroit rename(String name) {
		return new CourrierModeleDroit(name, null);
	}
}
