/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra.tables;


import fr.sdis83.remocra.db.converter.InstantConverter;
import fr.sdis83.remocra.db.model.remocra.Keys;
import fr.sdis83.remocra.db.model.remocra.Remocra;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.joda.time.Instant;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Document extends TableImpl<Record> {

	private static final long serialVersionUID = 1188179088;

	/**
	 * The reference instance of <code>remocra.document</code>
	 */
	public static final Document DOCUMENT = new Document();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>remocra.document.id</code>.
	 */
	public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>remocra.document.code</code>.
	 */
	public final TableField<Record, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

	/**
	 * The column <code>remocra.document.date</code>.
	 */
	public final TableField<Record, Instant> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "", new InstantConverter());

	/**
	 * The column <code>remocra.document.fichier</code>.
	 */
	public final TableField<Record, String> FICHIER = createField("fichier", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

	/**
	 * The column <code>remocra.document.repertoire</code>.
	 */
	public final TableField<Record, String> REPERTOIRE = createField("repertoire", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

	/**
	 * The column <code>remocra.document.type</code>.
	 */
	public final TableField<Record, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

	/**
	 * The column <code>remocra.document.date_doc</code>.
	 */
	public final TableField<Record, Instant> DATE_DOC = createField("date_doc", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "", new InstantConverter());

	/**
	 * Create a <code>remocra.document</code> table reference
	 */
	public Document() {
		this("document", null);
	}

	/**
	 * Create an aliased <code>remocra.document</code> table reference
	 */
	public Document(String alias) {
		this(alias, DOCUMENT);
	}

	private Document(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private Document(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Remocra.REMOCRA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Long> getIdentity() {
		return Keys.IDENTITY_DOCUMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.DOCUMENT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.DOCUMENT_PKEY, Keys.DOCUMENT_CODE_KEY, Keys.DOCUMENT_FICHIER_REPERTOIRE_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Document as(String alias) {
		return new Document(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Document rename(String name) {
		return new Document(name, null);
	}
}
