/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra.tables;


import fr.sdis83.remocra.db.model.remocra.Keys;
import fr.sdis83.remocra.db.model.remocra.Remocra;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * Document associé à une visite de contrôle réalisée sur une parcelle soumise 
 * à une obligation légale de débroussaillement
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OldebVisiteDocument extends TableImpl<Record> {

	private static final long serialVersionUID = 265032074;

	/**
	 * The reference instance of <code>remocra.oldeb_visite_document</code>
	 */
	public static final OldebVisiteDocument OLDEB_VISITE_DOCUMENT = new OldebVisiteDocument();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>remocra.oldeb_visite_document.id</code>.
	 */
	public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>remocra.oldeb_visite_document.document</code>.
	 */
	public final TableField<Record, Long> DOCUMENT = createField("document", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>remocra.oldeb_visite_document.visite</code>.
	 */
	public final TableField<Record, Long> VISITE = createField("visite", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>remocra.oldeb_visite_document</code> table reference
	 */
	public OldebVisiteDocument() {
		this("oldeb_visite_document", null);
	}

	/**
	 * Create an aliased <code>remocra.oldeb_visite_document</code> table reference
	 */
	public OldebVisiteDocument(String alias) {
		this(alias, OLDEB_VISITE_DOCUMENT);
	}

	private OldebVisiteDocument(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private OldebVisiteDocument(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Remocra.REMOCRA, aliased, parameters, "Document associé à une visite de contrôle réalisée sur une parcelle soumise à une obligation légale de débroussaillement");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Long> getIdentity() {
		return Keys.IDENTITY_OLDEB_VISITE_DOCUMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.OLDEB_VISITE_DOCUMENT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.OLDEB_VISITE_DOCUMENT_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<Record, ?>> getReferences() {
		return Arrays.<ForeignKey<Record, ?>>asList(Keys.OLDEB_VISITE_DOCUMENT__FK_OLDEB_VISITE_DOCUMENT_DOCUMENT, Keys.OLDEB_VISITE_DOCUMENT__FK_OLDEB_VISITE_DOCUMENT_VISITE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OldebVisiteDocument as(String alias) {
		return new OldebVisiteDocument(alias, this);
	}

	/**
	 * Rename this table
	 */
	public OldebVisiteDocument rename(String name) {
		return new OldebVisiteDocument(name, null);
	}
}
