/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra.tables;


import fr.sdis83.remocra.db.converter.InstantConverter;
import fr.sdis83.remocra.db.model.remocra.Keys;
import fr.sdis83.remocra.db.model.remocra.Remocra;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.joda.time.Instant;
import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SuiviPatches extends TableImpl<Record> {

	private static final long serialVersionUID = -1348996607;

	/**
	 * The reference instance of <code>remocra.suivi_patches</code>
	 */
	public static final SuiviPatches SUIVI_PATCHES = new SuiviPatches();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>remocra.suivi_patches.numero</code>.
	 */
	public final TableField<Record, Long> NUMERO = createField("numero", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>remocra.suivi_patches.description</code>.
	 */
	public final TableField<Record, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

	/**
	 * The column <code>remocra.suivi_patches.application</code>.
	 */
	public final TableField<Record, Instant> APPLICATION = createField("application", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "", new InstantConverter());

	/**
	 * Create a <code>remocra.suivi_patches</code> table reference
	 */
	public SuiviPatches() {
		this("suivi_patches", null);
	}

	/**
	 * Create an aliased <code>remocra.suivi_patches</code> table reference
	 */
	public SuiviPatches(String alias) {
		this(alias, SUIVI_PATCHES);
	}

	private SuiviPatches(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private SuiviPatches(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Remocra.REMOCRA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.SUIVI_PATCHES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.SUIVI_PATCHES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SuiviPatches as(String alias) {
		return new SuiviPatches(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SuiviPatches rename(String name) {
		return new SuiviPatches(name, null);
	}
}
