/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra.tables;


import fr.sdis83.remocra.db.model.remocra.Keys;
import fr.sdis83.remocra.db.model.remocra.Remocra;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * Type de suite donnée après une visite liée à une obligation légale de débroussaillement
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypeOldebSuite extends TableImpl<Record> {

	private static final long serialVersionUID = -317189352;

	/**
	 * The reference instance of <code>remocra.type_oldeb_suite</code>
	 */
	public static final TypeOldebSuite TYPE_OLDEB_SUITE = new TypeOldebSuite();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>remocra.type_oldeb_suite.id</code>.
	 */
	public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>remocra.type_oldeb_suite.actif</code>.
	 */
	public final TableField<Record, Boolean> ACTIF = createField("actif", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>remocra.type_oldeb_suite.code</code>.
	 */
	public final TableField<Record, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

	/**
	 * The column <code>remocra.type_oldeb_suite.nom</code>.
	 */
	public final TableField<Record, String> NOM = createField("nom", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

	/**
	 * Create a <code>remocra.type_oldeb_suite</code> table reference
	 */
	public TypeOldebSuite() {
		this("type_oldeb_suite", null);
	}

	/**
	 * Create an aliased <code>remocra.type_oldeb_suite</code> table reference
	 */
	public TypeOldebSuite(String alias) {
		this(alias, TYPE_OLDEB_SUITE);
	}

	private TypeOldebSuite(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private TypeOldebSuite(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Remocra.REMOCRA, aliased, parameters, "Type de suite donnée après une visite liée à une obligation légale de débroussaillement");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Long> getIdentity() {
		return Keys.IDENTITY_TYPE_OLDEB_SUITE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.TYPE_OLDEB_SUITE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.TYPE_OLDEB_SUITE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TypeOldebSuite as(String alias) {
		return new TypeOldebSuite(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TypeOldebSuite rename(String name) {
		return new TypeOldebSuite(name, null);
	}
}
