/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra.tables;


import fr.sdis83.remocra.db.model.remocra.Keys;
import fr.sdis83.remocra.db.model.remocra.Remocra;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypePermisInterservice extends TableImpl<Record> {

	private static final long serialVersionUID = -1487655825;

	/**
	 * The reference instance of <code>remocra.type_permis_interservice</code>
	 */
	public static final TypePermisInterservice TYPE_PERMIS_INTERSERVICE = new TypePermisInterservice();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	/**
	 * The column <code>remocra.type_permis_interservice.id</code>.
	 */
	public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>remocra.type_permis_interservice.actif</code>.
	 */
	public final TableField<Record, Boolean> ACTIF = createField("actif", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>remocra.type_permis_interservice.code</code>.
	 */
	public final TableField<Record, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>remocra.type_permis_interservice.nom</code>.
	 */
	public final TableField<Record, String> NOM = createField("nom", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

	/**
	 * The column <code>remocra.type_permis_interservice.pprif</code>.
	 */
	public final TableField<Record, Boolean> PPRIF = createField("pprif", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>remocra.type_permis_interservice</code> table reference
	 */
	public TypePermisInterservice() {
		this("type_permis_interservice", null);
	}

	/**
	 * Create an aliased <code>remocra.type_permis_interservice</code> table reference
	 */
	public TypePermisInterservice(String alias) {
		this(alias, TYPE_PERMIS_INTERSERVICE);
	}

	private TypePermisInterservice(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private TypePermisInterservice(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, Remocra.REMOCRA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<Record, Long> getIdentity() {
		return Keys.IDENTITY_TYPE_PERMIS_INTERSERVICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<Record> getPrimaryKey() {
		return Keys.TYPE_PERMIS_INTERSERVICE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.TYPE_PERMIS_INTERSERVICE_PKEY, Keys.TYPE_PERMIS_INTERSERVICE_CODE_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TypePermisInterservice as(String alias) {
		return new TypePermisInterservice(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TypePermisInterservice rename(String name) {
		return new TypePermisInterservice(name, null);
	}
}
