/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.tracabilite;


import fr.sdis83.remocra.db.model.tracabilite.tables.Hydrant;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in tracabilite
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table tracabilite.hydrant
	 */
	public static final Hydrant HYDRANT = fr.sdis83.remocra.db.model.tracabilite.tables.Hydrant.HYDRANT;
}
