# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.host_name = "remocra"
  config.vm.box = "box-cutter/centos67"

  # Ports
  config.vm.network :forwarded_port, guest: 5432, host: 5453
  config.vm.network :forwarded_port, guest: 8080, host: 8003
  config.vm.network :forwarded_port, guest: 8090, host: 8004
  config.vm.network :forwarded_port, guest: 80,   host: 8002
  config.vm.network :forwarded_port, guest: 443,  host: 8001

  # Répertoires synchronisés
  config.vm.synced_folder "livraison", "/livraison", :owner => 'root', create: true
  config.vm.synced_folder "..", "/projet", :owner => 'root', create: true

  # Provider
  config.vm.provider :virtualbox do |vb|
    vb.name = "remocra_ext"
    vb.memory = 2048
    vb.cpus = 4
  end

  # Redéfinition des paramètres (une fois)
  config.vm.provision "shell", inline: <<-SHELL
cat ~/.bashrc | grep SRC_SDIS > /dev/null
if [ $? -eq 0 ]; then
  # Variables déjà dans le profil, on ne va pas plus loin
  echo "root : pas d'ajout des variables dans le profil (déjà présentes)"
  exit 0
fi
# Ajout des variables dans le profil
echo "root : ajout des variables dans le profil"
cat << 'EOF' >> /root/.bashrc

### URL du site
URL_SITE="http://localhost:8080/remocra/"

### SDIS
export SRC_SDIS=83

### Base de données
export POSTGRES_DB_PASSWORD=5f5145fsdht
export REMOCRA_DB_PASSWORD=4sc4dsf86

### Tomcat
export TOMCAT_ADMIN_USERNAME=remocraadm
export TOMCAT_ADMIN_PASSWORD=remocraadmpwd1sd
export GEOSERVER_ADMIN_PASSWORD=de4df84ezf

### Utilisateurs
export APP_PASSWORD=remocrad41sq

### Courriels (par PDI)
export TECH_EMAIL=cva+remocra${SRC_SDIS}@atolcd.com

### Divers
export APP_IGNKEYS="fjwf53vbh2ikn9q009g6mi7f"

### Paramètres cachés réservés à un usage interne dans un contexte Box Vagrant par exemple
# (REMOCRA_FORCE_CREATE_DB_IF_ABSENT : true/false)
export REMOCRA_FORCE_CREATE_DB_IF_ABSENT=true

EOF
. /root/.bashrc
SHELL


  # Installation / mise à jour
  config.vm.provision "shell", path: "livraison/launcher.sh"

end
