/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.pdi;


import fr.sdis83.remocra.db.model.pdi.tables.ModeleMessage;
import fr.sdis83.remocra.db.model.pdi.tables.ModeleTraitement;
import fr.sdis83.remocra.db.model.pdi.tables.ModeleTraitementParametre;
import fr.sdis83.remocra.db.model.pdi.tables.Statut;
import fr.sdis83.remocra.db.model.pdi.tables.Traitement;
import fr.sdis83.remocra.db.model.pdi.tables.TraitementCc;
import fr.sdis83.remocra.db.model.pdi.tables.TraitementParametre;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>pdi</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<Record, Integer> IDENTITY_TRAITEMENT = Identities0.IDENTITY_TRAITEMENT;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<Record> MODELE_MESSAGE_PKEY = UniqueKeys0.MODELE_MESSAGE_PKEY;
	public static final UniqueKey<Record> MODELE_TRAITEMENT_PKEY = UniqueKeys0.MODELE_TRAITEMENT_PKEY;
	public static final UniqueKey<Record> MODELE_TRAITEMENT_PARAMETRE_PKEY = UniqueKeys0.MODELE_TRAITEMENT_PARAMETRE_PKEY;
	public static final UniqueKey<Record> STATUT_PKEY = UniqueKeys0.STATUT_PKEY;
	public static final UniqueKey<Record> TRAITEMENT_PKEY = UniqueKeys0.TRAITEMENT_PKEY;
	public static final UniqueKey<Record> TRAITEMENT_CC_PKEY = UniqueKeys0.TRAITEMENT_CC_PKEY;
	public static final UniqueKey<Record> TRAITEMENT_PARAMETRE_PKEY = UniqueKeys0.TRAITEMENT_PARAMETRE_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<Record, Record> MODELE_TRAITEMENT__FKD8399BB8FB49F7FF = ForeignKeys0.MODELE_TRAITEMENT__FKD8399BB8FB49F7FF;
	public static final ForeignKey<Record, Record> MODELE_TRAITEMENT__FKD8399BB880A2E237 = ForeignKeys0.MODELE_TRAITEMENT__FKD8399BB880A2E237;
	public static final ForeignKey<Record, Record> MODELE_TRAITEMENT_PARAMETRE__FK3D5405684675AFA4 = ForeignKeys0.MODELE_TRAITEMENT_PARAMETRE__FK3D5405684675AFA4;
	public static final ForeignKey<Record, Record> TRAITEMENT__FK923581F54675AFA4 = ForeignKeys0.TRAITEMENT__FK923581F54675AFA4;
	public static final ForeignKey<Record, Record> TRAITEMENT__FK923581F57CD7AABD = ForeignKeys0.TRAITEMENT__FK923581F57CD7AABD;
	public static final ForeignKey<Record, Record> TRAITEMENT_CC__FK923581F54675AFA4 = ForeignKeys0.TRAITEMENT_CC__FK923581F54675AFA4;
	public static final ForeignKey<Record, Record> TRAITEMENT_PARAMETRE__FKECA70365F5817DB6 = ForeignKeys0.TRAITEMENT_PARAMETRE__FKECA70365F5817DB6;
	public static final ForeignKey<Record, Record> TRAITEMENT_PARAMETRE__FKECA70365A667CB41 = ForeignKeys0.TRAITEMENT_PARAMETRE__FKECA70365A667CB41;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<Record, Integer> IDENTITY_TRAITEMENT = createIdentity(Traitement.TRAITEMENT, Traitement.TRAITEMENT.IDTRAITEMENT);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<Record> MODELE_MESSAGE_PKEY = createUniqueKey(ModeleMessage.MODELE_MESSAGE, ModeleMessage.MODELE_MESSAGE.IDMODELE);
		public static final UniqueKey<Record> MODELE_TRAITEMENT_PKEY = createUniqueKey(ModeleTraitement.MODELE_TRAITEMENT, ModeleTraitement.MODELE_TRAITEMENT.IDMODELE);
		public static final UniqueKey<Record> MODELE_TRAITEMENT_PARAMETRE_PKEY = createUniqueKey(ModeleTraitementParametre.MODELE_TRAITEMENT_PARAMETRE, ModeleTraitementParametre.MODELE_TRAITEMENT_PARAMETRE.IDPARAMETRE);
		public static final UniqueKey<Record> STATUT_PKEY = createUniqueKey(Statut.STATUT, Statut.STATUT.IDSTATUT);
		public static final UniqueKey<Record> TRAITEMENT_PKEY = createUniqueKey(Traitement.TRAITEMENT, Traitement.TRAITEMENT.IDTRAITEMENT);
		public static final UniqueKey<Record> TRAITEMENT_CC_PKEY = createUniqueKey(TraitementCc.TRAITEMENT_CC, TraitementCc.TRAITEMENT_CC.IDTRAITEMENT, TraitementCc.TRAITEMENT_CC.IDUTILISATEUR);
		public static final UniqueKey<Record> TRAITEMENT_PARAMETRE_PKEY = createUniqueKey(TraitementParametre.TRAITEMENT_PARAMETRE, TraitementParametre.TRAITEMENT_PARAMETRE.IDPARAMETRE, TraitementParametre.TRAITEMENT_PARAMETRE.IDTRAITEMENT);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<Record, Record> MODELE_TRAITEMENT__FKD8399BB8FB49F7FF = createForeignKey(fr.sdis83.remocra.db.model.pdi.Keys.MODELE_MESSAGE_PKEY, ModeleTraitement.MODELE_TRAITEMENT, ModeleTraitement.MODELE_TRAITEMENT.MESSAGE_ECHEC);
		public static final ForeignKey<Record, Record> MODELE_TRAITEMENT__FKD8399BB880A2E237 = createForeignKey(fr.sdis83.remocra.db.model.pdi.Keys.MODELE_MESSAGE_PKEY, ModeleTraitement.MODELE_TRAITEMENT, ModeleTraitement.MODELE_TRAITEMENT.MESSAGE_SUCCES);
		public static final ForeignKey<Record, Record> MODELE_TRAITEMENT_PARAMETRE__FK3D5405684675AFA4 = createForeignKey(fr.sdis83.remocra.db.model.pdi.Keys.MODELE_TRAITEMENT_PKEY, ModeleTraitementParametre.MODELE_TRAITEMENT_PARAMETRE, ModeleTraitementParametre.MODELE_TRAITEMENT_PARAMETRE.IDMODELE);
		public static final ForeignKey<Record, Record> TRAITEMENT__FK923581F54675AFA4 = createForeignKey(fr.sdis83.remocra.db.model.pdi.Keys.MODELE_TRAITEMENT_PKEY, Traitement.TRAITEMENT, Traitement.TRAITEMENT.IDMODELE);
		public static final ForeignKey<Record, Record> TRAITEMENT__FK923581F57CD7AABD = createForeignKey(fr.sdis83.remocra.db.model.pdi.Keys.STATUT_PKEY, Traitement.TRAITEMENT, Traitement.TRAITEMENT.IDSTATUT);
		public static final ForeignKey<Record, Record> TRAITEMENT_CC__FK923581F54675AFA4 = createForeignKey(fr.sdis83.remocra.db.model.pdi.Keys.TRAITEMENT_PKEY, TraitementCc.TRAITEMENT_CC, TraitementCc.TRAITEMENT_CC.IDTRAITEMENT);
		public static final ForeignKey<Record, Record> TRAITEMENT_PARAMETRE__FKECA70365F5817DB6 = createForeignKey(fr.sdis83.remocra.db.model.pdi.Keys.MODELE_TRAITEMENT_PARAMETRE_PKEY, TraitementParametre.TRAITEMENT_PARAMETRE, TraitementParametre.TRAITEMENT_PARAMETRE.IDPARAMETRE);
		public static final ForeignKey<Record, Record> TRAITEMENT_PARAMETRE__FKECA70365A667CB41 = createForeignKey(fr.sdis83.remocra.db.model.pdi.Keys.TRAITEMENT_PKEY, TraitementParametre.TRAITEMENT_PARAMETRE, TraitementParametre.TRAITEMENT_PARAMETRE.IDTRAITEMENT);
	}
}
