= SDIS Remocra - Manuel d'installation

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

:experimental:
:icons: font

:toc:

:numbered:

link:index{outfilesuffix}[Retour à l'accueil]

'''

== Dans une machine virtuelle ==

Le fichier ```vagrant_ext/Vagrantfile``` permet de créer rapidement une machine virtuelle link:https://www.virtualbox.org[VirtualBox] munie de remocra via link:https://www.vagrantup.com/downloads.html[Vagrant]. Pour tester :

* Compiler le projet via ```packaging/remocra-package.sh```
* Déposer l'archive générée (exemple : ```packaging/remocrapackage/20171108_remocrapackage0.9.14.zip```) dans ```vagrant_ext/livraison```
* Executer ```cd vagrant_ext && vagrant up```

Accès après l'installation :

* http://localhost:8002/remocra
* http://localhost:8002/geoserver

== Sur un serveur ==

Pour installer rapidement un serveur remocra, on réalise l'équivalent de ce qui est réalisé par Vagrant. A savoir :

* Partir d'un serveur CentOS 6X vierge
* Créer le répertoire d'accueil des éléments d'installation :
 
 mkdir /livraison

* Déposer les scripts du répertoire ```vagrant_ext/livraison``` :
** ```/livraison/install_base.sh```
** ```/livraison/install_remocra.sh```
** ```/livraison/launcher.sh```

* Rendre les scripts exécutables :

 chmod u+x /livraison/*.sh

* Déposer l'archive remocra. Exemple :
** ```/livraison/remocra 20171108_remocrapackage0.9.14.zip```

* Redéfinir les variables d'environnement de ```launcher.sh``` (mots de passe, mail, clé IGN, etc.)
** Par exemple, on ajoutera les surcharges dans ```~/.bashrc``` qu'on sourcera avant de lancer l'installation en exécutant ```. ~/.bashrc```

* Lancer l'installation :

 /livraison/launcher.sh 2>&1 | tee /livraison/launcher.log

Accès après l'installation :

* http://remocra.sdisxx.fr/remocra
* http://remocra.sdisxx.fr/geoserver


== Remarques ==

Si une erreur se produit, l'installation est immédiatement arrêtée. Le cas échéant, rechercher la cause de l'erreur, corriger manuellement les erreurs de manière à être dans un état cohérent et relancer l'installation.

Les *causes d'erreurs les plus courantes* sont les suivantes :

=== Tomcat n'a pas eu le temps de démarrer ===

* Détection : message obtenu dans le console lors de l'installation :
[source,ruby]
----
Stopping tomcat6: waiting for processes 43660 to exit
Starting tomcat6: ÉCHOUÉ
ABORTED - L'installation / mise à jour a été interrompue -
----

* Action : Redémarrer tomcat puis l'installation :
[source,ruby]
----
service tomcat6 restart && service tomcat6 status
/livraison/launcher.sh 2>&1 | tee /livraison/launcher.log
----

=== SELinux activé ===

* Détection : serveur inaccessible à la fin de l'installation malgré un message positif
* Action : désactiver SELinux

Désactiver SE Linux en modifiant le fichier :

./etc/selinux/config
[source,ruby]
----
SELINUX=disabled
----

Puis redémarrer le serveur avec la commande ```reboot```

Exemple de vérification avec la commande `sestatus && getenforce` :
[source,ruby]
----
SELinux status:                 disabled
Disabled
----


=== Hostname mal paramétré ===

* Détection : Message du type `Erreur: Exception envoyée par l'agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: XXXXX: XXXXX: Nom ou service inconnu` dans le fichier `/var/log/tomcat6/catalina.out`
* Action : paramétrer le `hostname`

Exemples de fichiers :

./etc/hosts
[source,ruby]
----
127.0.0.1   localhost localhost.localdomain remocra.sdisXX.fr
::1         localhost localhost.localdomain remocra.sdisXX.fr
----

./etc/sysconfig/network
[source,ruby]
----
NETWORKING=yes
HOSTNAME=remocra.sdisXX.fr
----

Puis redémarrer le serveur avec la commande `reboot`

Exemple de vérification avec la commande `hostname` :
[source,ruby]
----
remocra.sdisXX.fr
----
