/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlocDocumentProfilDroits implements Serializable {

	private static final long serialVersionUID = 1116042268;

	private Long blocDocument;
	private Long profilDroits;

	public BlocDocumentProfilDroits() {}

	public BlocDocumentProfilDroits(BlocDocumentProfilDroits value) {
		this.blocDocument = value.blocDocument;
		this.profilDroits = value.profilDroits;
	}

	public BlocDocumentProfilDroits(
		Long blocDocument,
		Long profilDroits
	) {
		this.blocDocument = blocDocument;
		this.profilDroits = profilDroits;
	}

	public Long getBlocDocument() {
		return this.blocDocument;
	}

	public BlocDocumentProfilDroits setBlocDocument(Long blocDocument) {
		this.blocDocument = blocDocument;
		return this;
	}

	public Long getProfilDroits() {
		return this.profilDroits;
	}

	public BlocDocumentProfilDroits setProfilDroits(Long profilDroits) {
		this.profilDroits = profilDroits;
		return this;
	}
}
