/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.joda.time.Instant;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailSave implements Serializable {

	private static final long serialVersionUID = 511428497;

	private Long    id;
	private String  corps;
	private String  destinataire;
	private String  destinataireEmail;
	private String  expediteur;
	private String  expediteurEmail;
	private Instant notification;
	private String  objet;
	private String  code;
	private Boolean accuserReception;

	public EmailSave() {}

	public EmailSave(EmailSave value) {
		this.id = value.id;
		this.corps = value.corps;
		this.destinataire = value.destinataire;
		this.destinataireEmail = value.destinataireEmail;
		this.expediteur = value.expediteur;
		this.expediteurEmail = value.expediteurEmail;
		this.notification = value.notification;
		this.objet = value.objet;
		this.code = value.code;
		this.accuserReception = value.accuserReception;
	}

	public EmailSave(
		Long    id,
		String  corps,
		String  destinataire,
		String  destinataireEmail,
		String  expediteur,
		String  expediteurEmail,
		Instant notification,
		String  objet,
		String  code,
		Boolean accuserReception
	) {
		this.id = id;
		this.corps = corps;
		this.destinataire = destinataire;
		this.destinataireEmail = destinataireEmail;
		this.expediteur = expediteur;
		this.expediteurEmail = expediteurEmail;
		this.notification = notification;
		this.objet = objet;
		this.code = code;
		this.accuserReception = accuserReception;
	}

	public Long getId() {
		return this.id;
	}

	public EmailSave setId(Long id) {
		this.id = id;
		return this;
	}

	public String getCorps() {
		return this.corps;
	}

	public EmailSave setCorps(String corps) {
		this.corps = corps;
		return this;
	}

	public String getDestinataire() {
		return this.destinataire;
	}

	public EmailSave setDestinataire(String destinataire) {
		this.destinataire = destinataire;
		return this;
	}

	public String getDestinataireEmail() {
		return this.destinataireEmail;
	}

	public EmailSave setDestinataireEmail(String destinataireEmail) {
		this.destinataireEmail = destinataireEmail;
		return this;
	}

	public String getExpediteur() {
		return this.expediteur;
	}

	public EmailSave setExpediteur(String expediteur) {
		this.expediteur = expediteur;
		return this;
	}

	public String getExpediteurEmail() {
		return this.expediteurEmail;
	}

	public EmailSave setExpediteurEmail(String expediteurEmail) {
		this.expediteurEmail = expediteurEmail;
		return this;
	}

	public Instant getNotification() {
		return this.notification;
	}

	public EmailSave setNotification(Instant notification) {
		this.notification = notification;
		return this;
	}

	public String getObjet() {
		return this.objet;
	}

	public EmailSave setObjet(String objet) {
		this.objet = objet;
		return this;
	}

	public String getCode() {
		return this.code;
	}

	public EmailSave setCode(String code) {
		this.code = code;
		return this;
	}

	public Boolean getAccuserReception() {
		return this.accuserReception;
	}

	public EmailSave setAccuserReception(Boolean accuserReception) {
		this.accuserReception = accuserReception;
		return this;
	}
}
