/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra.tables.pojos;


import com.vividsolutions.jts.geom.Geometry;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Aspiration des PENA
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HydrantAspiration implements Serializable {

	private static final long serialVersionUID = 2022489953;

	private Long     id;
	private String   numero;
	private Boolean  normalise;
	private Boolean  hauteur;
	private Long     typeAspiration;
	private Boolean  deporte;
	private Geometry geometrie;
	private Long     pena;
	private Integer  version;

	public HydrantAspiration() {}

	public HydrantAspiration(HydrantAspiration value) {
		this.id = value.id;
		this.numero = value.numero;
		this.normalise = value.normalise;
		this.hauteur = value.hauteur;
		this.typeAspiration = value.typeAspiration;
		this.deporte = value.deporte;
		this.geometrie = value.geometrie;
		this.pena = value.pena;
		this.version = value.version;
	}

	public HydrantAspiration(
		Long     id,
		String   numero,
		Boolean  normalise,
		Boolean  hauteur,
		Long     typeAspiration,
		Boolean  deporte,
		Geometry geometrie,
		Long     pena,
		Integer  version
	) {
		this.id = id;
		this.numero = numero;
		this.normalise = normalise;
		this.hauteur = hauteur;
		this.typeAspiration = typeAspiration;
		this.deporte = deporte;
		this.geometrie = geometrie;
		this.pena = pena;
		this.version = version;
	}

	public Long getId() {
		return this.id;
	}

	public HydrantAspiration setId(Long id) {
		this.id = id;
		return this;
	}

	public String getNumero() {
		return this.numero;
	}

	public HydrantAspiration setNumero(String numero) {
		this.numero = numero;
		return this;
	}

	public Boolean getNormalise() {
		return this.normalise;
	}

	public HydrantAspiration setNormalise(Boolean normalise) {
		this.normalise = normalise;
		return this;
	}

	public Boolean getHauteur() {
		return this.hauteur;
	}

	public HydrantAspiration setHauteur(Boolean hauteur) {
		this.hauteur = hauteur;
		return this;
	}

	public Long getTypeAspiration() {
		return this.typeAspiration;
	}

	public HydrantAspiration setTypeAspiration(Long typeAspiration) {
		this.typeAspiration = typeAspiration;
		return this;
	}

	public Boolean getDeporte() {
		return this.deporte;
	}

	public HydrantAspiration setDeporte(Boolean deporte) {
		this.deporte = deporte;
		return this;
	}

	public Geometry getGeometrie() {
		return this.geometrie;
	}

	public HydrantAspiration setGeometrie(Geometry geometrie) {
		this.geometrie = geometrie;
		return this;
	}

	public Long getPena() {
		return this.pena;
	}

	public HydrantAspiration setPena(Long pena) {
		this.pena = pena;
		return this;
	}

	public Integer getVersion() {
		return this.version;
	}

	public HydrantAspiration setVersion(Integer version) {
		this.version = version;
		return this;
	}
}
