/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.joda.time.Instant;


/**
 * Demande d'exécution d'un processus ETL dans le cadre d'une tâche planifiée 
 * ou d'une action d'un utilisateur
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessusEtl implements Serializable {

	private static final long serialVersionUID = 527355382;

	private Long    id;
	private Long    modele;
	private Long    statut;
	private Long    utilisateur;
	private Integer priorite;
	private Instant demande;
	private Instant execution;
	private String  code;

	public ProcessusEtl() {}

	public ProcessusEtl(ProcessusEtl value) {
		this.id = value.id;
		this.modele = value.modele;
		this.statut = value.statut;
		this.utilisateur = value.utilisateur;
		this.priorite = value.priorite;
		this.demande = value.demande;
		this.execution = value.execution;
		this.code = value.code;
	}

	public ProcessusEtl(
		Long    id,
		Long    modele,
		Long    statut,
		Long    utilisateur,
		Integer priorite,
		Instant demande,
		Instant execution,
		String  code
	) {
		this.id = id;
		this.modele = modele;
		this.statut = statut;
		this.utilisateur = utilisateur;
		this.priorite = priorite;
		this.demande = demande;
		this.execution = execution;
		this.code = code;
	}

	public Long getId() {
		return this.id;
	}

	public ProcessusEtl setId(Long id) {
		this.id = id;
		return this;
	}

	public Long getModele() {
		return this.modele;
	}

	public ProcessusEtl setModele(Long modele) {
		this.modele = modele;
		return this;
	}

	public Long getStatut() {
		return this.statut;
	}

	public ProcessusEtl setStatut(Long statut) {
		this.statut = statut;
		return this;
	}

	public Long getUtilisateur() {
		return this.utilisateur;
	}

	public ProcessusEtl setUtilisateur(Long utilisateur) {
		this.utilisateur = utilisateur;
		return this;
	}

	public Integer getPriorite() {
		return this.priorite;
	}

	public ProcessusEtl setPriorite(Integer priorite) {
		this.priorite = priorite;
		return this;
	}

	public Instant getDemande() {
		return this.demande;
	}

	public ProcessusEtl setDemande(Instant demande) {
		this.demande = demande;
		return this;
	}

	public Instant getExecution() {
		return this.execution;
	}

	public ProcessusEtl setExecution(Instant execution) {
		this.execution = execution;
		return this;
	}

	public String getCode() {
		return this.code;
	}

	public ProcessusEtl setCode(String code) {
		this.code = code;
		return this;
	}
}
