/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Paramètre associé à un modèle de requête
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessusEtlModeleParametre implements Serializable {

	private static final long serialVersionUID = 580648036;

	private Long    id;
	private String  nom;
	private String  typeValeur;
	private Boolean obligatoire;
	private String  sourceSql;
	private String  sourceSqlValeur;
	private String  sourceSqlLibelle;
	private String  formulaireEtiquette;
	private String  formulaireTypeControle;
	private Long    formulaireNumOrdre;
	private String  formulaireValeurDefaut;
	private Long    modele;

	public ProcessusEtlModeleParametre() {}

	public ProcessusEtlModeleParametre(ProcessusEtlModeleParametre value) {
		this.id = value.id;
		this.nom = value.nom;
		this.typeValeur = value.typeValeur;
		this.obligatoire = value.obligatoire;
		this.sourceSql = value.sourceSql;
		this.sourceSqlValeur = value.sourceSqlValeur;
		this.sourceSqlLibelle = value.sourceSqlLibelle;
		this.formulaireEtiquette = value.formulaireEtiquette;
		this.formulaireTypeControle = value.formulaireTypeControle;
		this.formulaireNumOrdre = value.formulaireNumOrdre;
		this.formulaireValeurDefaut = value.formulaireValeurDefaut;
		this.modele = value.modele;
	}

	public ProcessusEtlModeleParametre(
		Long    id,
		String  nom,
		String  typeValeur,
		Boolean obligatoire,
		String  sourceSql,
		String  sourceSqlValeur,
		String  sourceSqlLibelle,
		String  formulaireEtiquette,
		String  formulaireTypeControle,
		Long    formulaireNumOrdre,
		String  formulaireValeurDefaut,
		Long    modele
	) {
		this.id = id;
		this.nom = nom;
		this.typeValeur = typeValeur;
		this.obligatoire = obligatoire;
		this.sourceSql = sourceSql;
		this.sourceSqlValeur = sourceSqlValeur;
		this.sourceSqlLibelle = sourceSqlLibelle;
		this.formulaireEtiquette = formulaireEtiquette;
		this.formulaireTypeControle = formulaireTypeControle;
		this.formulaireNumOrdre = formulaireNumOrdre;
		this.formulaireValeurDefaut = formulaireValeurDefaut;
		this.modele = modele;
	}

	public Long getId() {
		return this.id;
	}

	public ProcessusEtlModeleParametre setId(Long id) {
		this.id = id;
		return this;
	}

	public String getNom() {
		return this.nom;
	}

	public ProcessusEtlModeleParametre setNom(String nom) {
		this.nom = nom;
		return this;
	}

	public String getTypeValeur() {
		return this.typeValeur;
	}

	public ProcessusEtlModeleParametre setTypeValeur(String typeValeur) {
		this.typeValeur = typeValeur;
		return this;
	}

	public Boolean getObligatoire() {
		return this.obligatoire;
	}

	public ProcessusEtlModeleParametre setObligatoire(Boolean obligatoire) {
		this.obligatoire = obligatoire;
		return this;
	}

	public String getSourceSql() {
		return this.sourceSql;
	}

	public ProcessusEtlModeleParametre setSourceSql(String sourceSql) {
		this.sourceSql = sourceSql;
		return this;
	}

	public String getSourceSqlValeur() {
		return this.sourceSqlValeur;
	}

	public ProcessusEtlModeleParametre setSourceSqlValeur(String sourceSqlValeur) {
		this.sourceSqlValeur = sourceSqlValeur;
		return this;
	}

	public String getSourceSqlLibelle() {
		return this.sourceSqlLibelle;
	}

	public ProcessusEtlModeleParametre setSourceSqlLibelle(String sourceSqlLibelle) {
		this.sourceSqlLibelle = sourceSqlLibelle;
		return this;
	}

	public String getFormulaireEtiquette() {
		return this.formulaireEtiquette;
	}

	public ProcessusEtlModeleParametre setFormulaireEtiquette(String formulaireEtiquette) {
		this.formulaireEtiquette = formulaireEtiquette;
		return this;
	}

	public String getFormulaireTypeControle() {
		return this.formulaireTypeControle;
	}

	public ProcessusEtlModeleParametre setFormulaireTypeControle(String formulaireTypeControle) {
		this.formulaireTypeControle = formulaireTypeControle;
		return this;
	}

	public Long getFormulaireNumOrdre() {
		return this.formulaireNumOrdre;
	}

	public ProcessusEtlModeleParametre setFormulaireNumOrdre(Long formulaireNumOrdre) {
		this.formulaireNumOrdre = formulaireNumOrdre;
		return this;
	}

	public String getFormulaireValeurDefaut() {
		return this.formulaireValeurDefaut;
	}

	public ProcessusEtlModeleParametre setFormulaireValeurDefaut(String formulaireValeurDefaut) {
		this.formulaireValeurDefaut = formulaireValeurDefaut;
		return this;
	}

	public Long getModele() {
		return this.modele;
	}

	public ProcessusEtlModeleParametre setModele(Long modele) {
		this.modele = modele;
		return this;
	}
}
