/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypeRciPromPartition implements Serializable {

	private static final long serialVersionUID = 1074402200;

	private Long    id;
	private Boolean actif;
	private String  code;
	private String  nom;
	private Integer version;
	private Long    famille;

	public TypeRciPromPartition() {}

	public TypeRciPromPartition(TypeRciPromPartition value) {
		this.id = value.id;
		this.actif = value.actif;
		this.code = value.code;
		this.nom = value.nom;
		this.version = value.version;
		this.famille = value.famille;
	}

	public TypeRciPromPartition(
		Long    id,
		Boolean actif,
		String  code,
		String  nom,
		Integer version,
		Long    famille
	) {
		this.id = id;
		this.actif = actif;
		this.code = code;
		this.nom = nom;
		this.version = version;
		this.famille = famille;
	}

	public Long getId() {
		return this.id;
	}

	public TypeRciPromPartition setId(Long id) {
		this.id = id;
		return this;
	}

	public Boolean getActif() {
		return this.actif;
	}

	public TypeRciPromPartition setActif(Boolean actif) {
		this.actif = actif;
		return this;
	}

	public String getCode() {
		return this.code;
	}

	public TypeRciPromPartition setCode(String code) {
		this.code = code;
		return this;
	}

	public String getNom() {
		return this.nom;
	}

	public TypeRciPromPartition setNom(String nom) {
		this.nom = nom;
		return this;
	}

	public Integer getVersion() {
		return this.version;
	}

	public TypeRciPromPartition setVersion(Integer version) {
		this.version = version;
		return this;
	}

	public Long getFamille() {
		return this.famille;
	}

	public TypeRciPromPartition setFamille(Long famille) {
		this.famille = famille;
		return this;
	}
}
