/**
 * This class is generated by jOOQ
 */
package fr.sdis83.remocra.db.model.remocra.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypeHydrantModele implements Serializable {

	private static final long serialVersionUID = 1146981866;

	private Long    id;
	private Boolean actif;
	private String  code;
	private String  nom;
	private Integer version;
	private Long    marque;

	public TypeHydrantModele() {}

	public TypeHydrantModele(TypeHydrantModele value) {
		this.id = value.id;
		this.actif = value.actif;
		this.code = value.code;
		this.nom = value.nom;
		this.version = value.version;
		this.marque = value.marque;
	}

	public TypeHydrantModele(
		Long    id,
		Boolean actif,
		String  code,
		String  nom,
		Integer version,
		Long    marque
	) {
		this.id = id;
		this.actif = actif;
		this.code = code;
		this.nom = nom;
		this.version = version;
		this.marque = marque;
	}

	public Long getId() {
		return this.id;
	}

	public TypeHydrantModele setId(Long id) {
		this.id = id;
		return this;
	}

	public Boolean getActif() {
		return this.actif;
	}

	public TypeHydrantModele setActif(Boolean actif) {
		this.actif = actif;
		return this;
	}

	public String getCode() {
		return this.code;
	}

	public TypeHydrantModele setCode(String code) {
		this.code = code;
		return this;
	}

	public String getNom() {
		return this.nom;
	}

	public TypeHydrantModele setNom(String nom) {
		this.nom = nom;
		return this;
	}

	public Integer getVersion() {
		return this.version;
	}

	public TypeHydrantModele setVersion(Integer version) {
		this.version = version;
		return this;
	}

	public Long getMarque() {
		return this.marque;
	}

	public TypeHydrantModele setMarque(Long marque) {
		this.marque = marque;
		return this;
	}
}
