/*
 * This file is generated by jOOQ.
 */
package fr.sdis83.remocra.db.model.remocra.tables;


import fr.sdis83.remocra.db.converter.TimestampToInstantConverter;
import fr.sdis83.remocra.db.model.remocra.Indexes;
import fr.sdis83.remocra.db.model.remocra.Keys;
import fr.sdis83.remocra.db.model.remocra.Remocra;

import java.time.Instant;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DebitSimultaneMesure extends TableImpl<Record> {

    private static final long serialVersionUID = -290151088;

    /**
     * The reference instance of <code>remocra.debit_simultane_mesure</code>
     */
    public static final DebitSimultaneMesure DEBIT_SIMULTANE_MESURE = new DebitSimultaneMesure();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>remocra.debit_simultane_mesure.id</code>.
     */
    public final TableField<Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('remocra.debit_simultane_mesure_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>remocra.debit_simultane_mesure.debit_simultane</code>.
     */
    public final TableField<Record, Long> DEBIT_SIMULTANE = createField("debit_simultane", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>remocra.debit_simultane_mesure.debit_requis</code>.
     */
    public final TableField<Record, Integer> DEBIT_REQUIS = createField("debit_requis", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>remocra.debit_simultane_mesure.debit_mesure</code>.
     */
    public final TableField<Record, Integer> DEBIT_MESURE = createField("debit_mesure", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>remocra.debit_simultane_mesure.date_mesure</code>.
     */
    public final TableField<Record, Instant> DATE_MESURE = createField("date_mesure", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "", new TimestampToInstantConverter());

    /**
     * The column <code>remocra.debit_simultane_mesure.debit_retenu</code>.
     */
    public final TableField<Record, Integer> DEBIT_RETENU = createField("debit_retenu", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>remocra.debit_simultane_mesure.irv</code>.
     */
    public final TableField<Record, Boolean> IRV = createField("irv", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>remocra.debit_simultane_mesure.commentaire</code>.
     */
    public final TableField<Record, String> COMMENTAIRE = createField("commentaire", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>remocra.debit_simultane_mesure</code> table reference
     */
    public DebitSimultaneMesure() {
        this(DSL.name("debit_simultane_mesure"), null);
    }

    /**
     * Create an aliased <code>remocra.debit_simultane_mesure</code> table reference
     */
    public DebitSimultaneMesure(String alias) {
        this(DSL.name(alias), DEBIT_SIMULTANE_MESURE);
    }

    /**
     * Create an aliased <code>remocra.debit_simultane_mesure</code> table reference
     */
    public DebitSimultaneMesure(Name alias) {
        this(alias, DEBIT_SIMULTANE_MESURE);
    }

    private DebitSimultaneMesure(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private DebitSimultaneMesure(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> DebitSimultaneMesure(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, DEBIT_SIMULTANE_MESURE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Remocra.REMOCRA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DEBIT_SIMULTANE_MESURE_DEBIT_SIMULTANE_IDX, Indexes.DEBIT_SIMULTANE_MESURE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Record, Long> getIdentity() {
        return Keys.IDENTITY_DEBIT_SIMULTANE_MESURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.DEBIT_SIMULTANE_MESURE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.DEBIT_SIMULTANE_MESURE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.DEBIT_SIMULTANE_MESURE__FK_DEBIT_SIMULTANE);
    }

    public DebitSimultane debitSimultane() {
        return new DebitSimultane(this, Keys.DEBIT_SIMULTANE_MESURE__FK_DEBIT_SIMULTANE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DebitSimultaneMesure as(String alias) {
        return new DebitSimultaneMesure(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DebitSimultaneMesure as(Name alias) {
        return new DebitSimultaneMesure(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DebitSimultaneMesure rename(String name) {
        return new DebitSimultaneMesure(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DebitSimultaneMesure rename(Name name) {
        return new DebitSimultaneMesure(name, null);
    }
}
