/*
 * This file is generated by jOOQ.
 */
package fr.sdis83.remocra.db.model.remocra.tables;


import fr.sdis83.remocra.db.model.remocra.Indexes;
import fr.sdis83.remocra.db.model.remocra.Keys;
import fr.sdis83.remocra.db.model.remocra.Remocra;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Valeur de paramètre par défaut à utiliser lors d'une demande de processus 
 * planifié
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessusEtlPlanificationParametre extends TableImpl<Record> {

    private static final long serialVersionUID = -1968232942;

    /**
     * The reference instance of <code>remocra.processus_etl_planification_parametre</code>
     */
    public static final ProcessusEtlPlanificationParametre PROCESSUS_ETL_PLANIFICATION_PARAMETRE = new ProcessusEtlPlanificationParametre();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>remocra.processus_etl_planification_parametre.processus_etl_planification</code>. Processus planifié associé
     */
    public final TableField<Record, Long> PROCESSUS_ETL_PLANIFICATION = createField("processus_etl_planification", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "Processus planifié associé");

    /**
     * The column <code>remocra.processus_etl_planification_parametre.parametre</code>. Paramètre de processus planifié associé
     */
    public final TableField<Record, Long> PARAMETRE = createField("parametre", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "Paramètre de processus planifié associé");

    /**
     * The column <code>remocra.processus_etl_planification_parametre.valeur</code>. Valeur du paramètre
     */
    public final TableField<Record, String> VALEUR = createField("valeur", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "Valeur du paramètre");

    /**
     * Create a <code>remocra.processus_etl_planification_parametre</code> table reference
     */
    public ProcessusEtlPlanificationParametre() {
        this(DSL.name("processus_etl_planification_parametre"), null);
    }

    /**
     * Create an aliased <code>remocra.processus_etl_planification_parametre</code> table reference
     */
    public ProcessusEtlPlanificationParametre(String alias) {
        this(DSL.name(alias), PROCESSUS_ETL_PLANIFICATION_PARAMETRE);
    }

    /**
     * Create an aliased <code>remocra.processus_etl_planification_parametre</code> table reference
     */
    public ProcessusEtlPlanificationParametre(Name alias) {
        this(alias, PROCESSUS_ETL_PLANIFICATION_PARAMETRE);
    }

    private ProcessusEtlPlanificationParametre(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private ProcessusEtlPlanificationParametre(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Valeur de paramètre par défaut à utiliser lors d'une demande de processus planifié"));
    }

    public <O extends Record> ProcessusEtlPlanificationParametre(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, PROCESSUS_ETL_PLANIFICATION_PARAMETRE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Remocra.REMOCRA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PROCESSUS_ETL_PLANIFICATION_PARAMETRE_PARAMETRE_IDX, Indexes.PROCESSUS_ETL_PLANIFICATION_PARAMETRE_PK, Indexes.PROCESSUS_ETL_PLANIFICATION_PARAMETRE_PROCESSUS_ETL_PLANIFICATI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.PROCESSUS_ETL_PLANIFICATION_PARAMETRE_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.PROCESSUS_ETL_PLANIFICATION_PARAMETRE_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.PROCESSUS_ETL_PLANIFICATION_PARAMETRE__PROCESSUS_ETL_PLANIFICATION_PARAMETRE_PROCESSUS_ETL_PLANIFICATI, Keys.PROCESSUS_ETL_PLANIFICATION_PARAMETRE__PROCESSUS_ETL_PLANIFICATION_PARAMETRE_PARAMETRE);
    }

    public ProcessusEtlPlanification processusEtlPlanification() {
        return new ProcessusEtlPlanification(this, Keys.PROCESSUS_ETL_PLANIFICATION_PARAMETRE__PROCESSUS_ETL_PLANIFICATION_PARAMETRE_PROCESSUS_ETL_PLANIFICATI);
    }

    public ProcessusEtlModeleParametre processusEtlModeleParametre() {
        return new ProcessusEtlModeleParametre(this, Keys.PROCESSUS_ETL_PLANIFICATION_PARAMETRE__PROCESSUS_ETL_PLANIFICATION_PARAMETRE_PARAMETRE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessusEtlPlanificationParametre as(String alias) {
        return new ProcessusEtlPlanificationParametre(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessusEtlPlanificationParametre as(Name alias) {
        return new ProcessusEtlPlanificationParametre(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessusEtlPlanificationParametre rename(String name) {
        return new ProcessusEtlPlanificationParametre(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessusEtlPlanificationParametre rename(Name name) {
        return new ProcessusEtlPlanificationParametre(name, null);
    }
}
