/*
 * This file is generated by jOOQ.
 */
package fr.sdis83.remocra.db.model.remocra.tables;


import fr.sdis83.remocra.db.model.remocra.Indexes;
import fr.sdis83.remocra.db.model.remocra.Keys;
import fr.sdis83.remocra.db.model.remocra.Remocra;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Profil de droit autorisé pour accéder à la catégorie d'évènement en création
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypeCriseEvenementDroit extends TableImpl<Record> {

    private static final long serialVersionUID = -1719047054;

    /**
     * The reference instance of <code>remocra.type_crise_evenement_droit</code>
     */
    public static final TypeCriseEvenementDroit TYPE_CRISE_EVENEMENT_DROIT = new TypeCriseEvenementDroit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>remocra.type_crise_evenement_droit.categorie_evenement</code>. Identifiant de la catégorie
     */
    public final TableField<Record, Long> CATEGORIE_EVENEMENT = createField("categorie_evenement", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "Identifiant de la catégorie");

    /**
     * The column <code>remocra.type_crise_evenement_droit.profil_droit</code>. Identifiant du profil de droit autorisé
     */
    public final TableField<Record, Long> PROFIL_DROIT = createField("profil_droit", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "Identifiant du profil de droit autorisé");

    /**
     * Create a <code>remocra.type_crise_evenement_droit</code> table reference
     */
    public TypeCriseEvenementDroit() {
        this(DSL.name("type_crise_evenement_droit"), null);
    }

    /**
     * Create an aliased <code>remocra.type_crise_evenement_droit</code> table reference
     */
    public TypeCriseEvenementDroit(String alias) {
        this(DSL.name(alias), TYPE_CRISE_EVENEMENT_DROIT);
    }

    /**
     * Create an aliased <code>remocra.type_crise_evenement_droit</code> table reference
     */
    public TypeCriseEvenementDroit(Name alias) {
        this(alias, TYPE_CRISE_EVENEMENT_DROIT);
    }

    private TypeCriseEvenementDroit(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private TypeCriseEvenementDroit(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Profil de droit autorisé pour accéder à la catégorie d'évènement en création"));
    }

    public <O extends Record> TypeCriseEvenementDroit(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, TYPE_CRISE_EVENEMENT_DROIT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Remocra.REMOCRA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TYPE_CRISE_EVENEMENT_DROIT_CATEGORIE_EVENEMENT_IDX, Indexes.TYPE_CRISE_EVENEMENT_DROIT_PKEY, Indexes.TYPE_CRISE_EVENEMENT_DROIT_PROFIL_DROIT_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.TYPE_CRISE_EVENEMENT_DROIT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.TYPE_CRISE_EVENEMENT_DROIT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.TYPE_CRISE_EVENEMENT_DROIT__TYPE_CRISE_EVENEMENT_DROIT_CATEGORIE_EVENEMENT_FK, Keys.TYPE_CRISE_EVENEMENT_DROIT__TYPE_CRISE_EVENEMENT_DROIT_DROIT_FK);
    }

    public TypeCriseCategorieEvenement typeCriseCategorieEvenement() {
        return new TypeCriseCategorieEvenement(this, Keys.TYPE_CRISE_EVENEMENT_DROIT__TYPE_CRISE_EVENEMENT_DROIT_CATEGORIE_EVENEMENT_FK);
    }

    public ProfilDroit profilDroit() {
        return new ProfilDroit(this, Keys.TYPE_CRISE_EVENEMENT_DROIT__TYPE_CRISE_EVENEMENT_DROIT_DROIT_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeCriseEvenementDroit as(String alias) {
        return new TypeCriseEvenementDroit(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeCriseEvenementDroit as(Name alias) {
        return new TypeCriseEvenementDroit(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TypeCriseEvenementDroit rename(String name) {
        return new TypeCriseEvenementDroit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TypeCriseEvenementDroit rename(Name name) {
        return new TypeCriseEvenementDroit(name, null);
    }
}
