/*
 * This file is generated by jOOQ.
 */
package fr.sdis83.remocra.db.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements Serializable {

    private static final long serialVersionUID = 901319034;

    private Long    id;
    private String  nom;
    private Integer version;
    private Boolean actif;
    private String  code;
    private Long    thematique;

    public Role() {}

    public Role(Role value) {
        this.id = value.id;
        this.nom = value.nom;
        this.version = value.version;
        this.actif = value.actif;
        this.code = value.code;
        this.thematique = value.thematique;
    }

    public Role(
        Long    id,
        String  nom,
        Integer version,
        Boolean actif,
        String  code,
        Long    thematique
    ) {
        this.id = id;
        this.nom = nom;
        this.version = version;
        this.actif = actif;
        this.code = code;
        this.thematique = thematique;
    }

    public Long getId() {
        return this.id;
    }

    public Role setId(Long id) {
        this.id = id;
        return this;
    }

    public String getNom() {
        return this.nom;
    }

    public Role setNom(String nom) {
        this.nom = nom;
        return this;
    }

    public Integer getVersion() {
        return this.version;
    }

    public Role setVersion(Integer version) {
        this.version = version;
        return this;
    }

    public Boolean getActif() {
        return this.actif;
    }

    public Role setActif(Boolean actif) {
        this.actif = actif;
        return this;
    }

    public String getCode() {
        return this.code;
    }

    public Role setCode(String code) {
        this.code = code;
        return this;
    }

    public Long getThematique() {
        return this.thematique;
    }

    public Role setThematique(Long thematique) {
        this.thematique = thematique;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(id);
        sb.append(", ").append(nom);
        sb.append(", ").append(version);
        sb.append(", ").append(actif);
        sb.append(", ").append(code);
        sb.append(", ").append(thematique);

        sb.append(")");
        return sb.toString();
    }
}
